<?php 
	$show_list = false;
	if ($wo['group_profile']['privacy'] == 1) {
		$show_list = true;
	} else if ($wo['group_profile']['privacy'] == 2) {
		if (!Wo_IsGroupOnwer($wo['group_profile']['id'])) {
			if (Wo_IsGroupJoined($wo['group_profile']['id'])) {
				$show_list = true;
			}
		} else {
			$show_list = true;
		}
	}  
?>
<?php 
	$group_privacy = $wo['lang']['public'];
	$group_icon = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M6.235 6.453a8 8 0 0 0 8.817 12.944c.115-.75-.137-1.47-.24-1.722-.23-.56-.988-1.517-2.253-2.844-.338-.355-.316-.628-.195-1.437l.013-.091c.082-.554.22-.882 2.085-1.178.948-.15 1.197.228 1.542.753l.116.172c.328.48.571.59.938.756.165.075.37.17.645.325.652.373.652.794.652 1.716v.105c0 .391-.038.735-.098 1.034a8.002 8.002 0 0 0-3.105-12.341c-.553.373-1.312.902-1.577 1.265-.135.185-.327 1.132-.95 1.21-.162.02-.381.006-.613-.009-.622-.04-1.472-.095-1.744.644-.173.468-.203 1.74.356 2.4.09.105.107.3.046.519-.08.287-.241.462-.292.498-.096-.056-.288-.279-.419-.43-.313-.365-.705-.82-1.211-.96-.184-.051-.386-.093-.583-.135-.549-.115-1.17-.246-1.315-.554-.106-.226-.105-.537-.105-.865 0-.417 0-.888-.204-1.345a1.276 1.276 0 0 0-.306-.43zM12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10z"></path></svg>';
	if ($wo['group_profile']['privacy'] == 2) {
		$group_privacy = $wo['lang']['private'];
		$group_icon = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M6 8V7a6 6 0 1 1 12 0v1h2a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1h2zm13 2H5v10h14V10zm-8 5.732a2 2 0 1 1 2 0V18h-2v-2.268zM8 8h8V7a4 4 0 1 0-8 0v1z"></path></svg>';
	}
?>
<div class="page-margin wo_group_profile" data-page="group" data-id="<?php echo $wo['group_profile']['id'];?>">
	<div class="container-fluid tag_cont_fluid">
		<div class="profile-container tag_cover_bg">
			<button class="btn btn-mat btn_goback" onclick="window.history.back();"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M19 11H7.83l4.88-4.88c.39-.39.39-1.03 0-1.42-.39-.39-1.02-.39-1.41 0l-6.59 6.59c-.39.39-.39 1.02 0 1.41l6.59 6.59c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L7.83 13H19c.55 0 1-.45 1-1s-.45-1-1-1z"></path></svg></button>
			<div class="tag_cover_sec_bg">
				<img src="<?php echo $wo['group_profile']['cover']?>">
				<div class="tag_cover_bg_grad"></div>
			</div>
			<div class="container">
				<div class="card hovercard">
					<div class="wow_content cardheader user-cover">
						<?php if(Wo_IsGroupOnwer($wo['group_profile']['id']) === true) { ?>
							<form action="#" method="post" class="profile-cover-changer">
								<span class="btn btn-file btn-mat">
									<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M23 18V6c0-1.1-.9-2-2-2H3c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2zM8.9 12.98l2.1 2.53 3.1-3.99c.2-.26.6-.26.8.01l3.51 4.68c.25.33.01.8-.4.8H6.02c-.42 0-.65-.48-.39-.81L8.12 13c.19-.26.57-.27.78-.02z"></path></svg> <?php echo $wo['lang']['cover']?>
									<input type="file" name="cover" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileCover();">
								</span>
								<input type="hidden" name="group_id" id="group-id" value="<?php echo $wo['group_profile']['id'];?>">
							</form>
						<?php } ?>
						<div class="user-cover-uploading-progress">
							<div class="pace-activity-parent"><div class="pace-activity"></div></div>
						</div>
						<img id="cover-image" src="<?php echo $wo['group_profile']['cover']?>" alt="<?php echo $wo['group_profile']['name']?>"/>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="valign wow_content p15 tag_event_name_hdr tag_group_name_hdr">
				<div class="event-info-cont-small">
					<div class="user-avatar">
						<div class="user-avatar-uploading-container">
							<div class="pace-activity-parent"><div class="pace-activity"></div></div>
						</div>
						<img id="group-avatar-image" alt="<?php echo $wo['group_profile']['name']?>" src="<?php echo $wo['group_profile']['avatar']?>"/>
						<?php if(Wo_IsGroupOnwer($wo['group_profile']['id']) === true) { ?>
						<form action="#" method="post" class="profile-avatar-changer">
							<span class="btn btn-file btn-mat">
								<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24" fill="currentColor"><path d="M0 0h24v24H0V0z" fill="none"></path><circle cx="12" cy="12" r="3"></circle><path d="M20 4h-3.17l-1.24-1.35c-.37-.41-.91-.65-1.47-.65H9.88c-.56 0-1.1.24-1.48.65L7.17 4H4c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm-8 13c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5z"></path></svg>
								<input type="file" name="avatar" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileAvatar();">
							</span>
							<input type="hidden" name="group_id" id="group-id" value="<?php echo $wo['group_profile']['id'];?>">
						</form>
						<?php } ?>
					</div>
					<h3><?php echo $wo['group_profile']['name']; ?></h3>
					<div class="event_cdown"><?php echo Wo_CountGroupMembers($wo['group_profile']['id']);?> <?php echo $wo['lang']['members'];?></div>
				</div>
				<div class="wow_event_page_btns">
					<span class="user-follow-button group-join-btn">
						<?php echo Wo_GetJoinButton($wo['group_profile']['id']);?>
					</span>
					<?php if (Wo_IsGroupOnwer($wo['group_profile']['id'])) { ?>
						<a href="<?php echo Wo_SeoLink('index.php?link1=group-setting&group=' .  $wo['group_profile']['group_name']); ?>" data-ajax="?link1=group-setting&group=<?php echo $wo['group_profile']['group_name'];?>" class="btn btn-default btn-mat"><?php echo $wo['lang']['edit']; ?></a>
					<?php } ?>
				</div>
			</div>
		</div>
		<div class="container">
			<?php if ($wo['group_profile']['privacy'] == 2 && Wo_IsGroupOnwer($wo['group_profile']['id']) === false && Wo_IsGroupJoined($wo['group_profile']['id']) === false) { ?>
				<div class="row">
					<div class="col-lg-2"></div>
					<div class="col-lg-8">
						<div class="page-margin wow_content p15">
							<div class="event_info_blocks">
								<div><?php echo $group_icon; ?> <?php echo $group_privacy; ?></div>
								<div>
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M9.55 11.5a2.25 2.25 0 1 1 0-4.5 2.25 2.25 0 0 1 0 4.5zm.45 8.248V16.4c0-.488.144-.937.404-1.338a6.473 6.473 0 0 0-5.033 1.417A8.012 8.012 0 0 0 10 19.749zM4.453 14.66A8.462 8.462 0 0 1 9.5 13c1.043 0 2.043.188 2.967.532.878-.343 1.925-.532 3.033-.532 1.66 0 3.185.424 4.206 1.156a8 8 0 1 0-15.253.504zm14.426 1.426C18.486 15.553 17.171 15 15.5 15c-2.006 0-3.5.797-3.5 1.4V20a7.996 7.996 0 0 0 6.88-3.914zM12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm3.5-9.5a2 2 0 1 1 0-4 2 2 0 0 1 0 4z"></path></svg> <?php echo Wo_CountGroupMembers($wo['group_profile']['id']);?> <?php echo $wo['lang']['members'];?>
								</div>
								<div>
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M10.9 2.1l9.899 1.415 1.414 9.9-9.192 9.192a1 1 0 0 1-1.414 0l-9.9-9.9a1 1 0 0 1 0-1.414L10.9 2.1zm.707 2.122L3.828 12l8.486 8.485 7.778-7.778-1.06-7.425-7.425-1.06zm2.12 6.364a2 2 0 1 1 2.83-2.829 2 2 0 0 1-2.83 2.829z"></path></svg> <?php echo $wo['group_profile']['category']; ?>
								</div>
								<?php if (!empty($wo['group_profile']['group_sub_category'])) { ?>
									<div>
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo $wo['lang']['sub_category']; ?>"><path fill="currentColor" d="M10.9 2.1l9.899 1.415 1.414 9.9-9.192 9.192a1 1 0 0 1-1.414 0l-9.9-9.9a1 1 0 0 1 0-1.414L10.9 2.1zm.707 2.122L3.828 12l8.486 8.485 7.778-7.778-1.06-7.425-7.425-1.06zm2.12 6.364a2 2 0 1 1 2.83-2.829 2 2 0 0 1-2.83 2.829z"></path></svg> <?php echo $wo['group_profile']['group_sub_category']; ?>
									</div>
								<?php } ?>
								<div>
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M20 22H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1zm-1-2V4H5v16h14zM8 7h8v2H8V7zm0 4h8v2H8v-2zm0 4h5v2H8v-2z"></path></svg> <?php echo Wo_CountGroupPosts($wo['group_profile']['id']);?> <?php echo $wo['lang']['posts']; ?>
								</div>
								<?php if(!empty($wo['group_profile']['about'])) {  ?>
									<div>
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-2a8 8 0 1 0 0-16 8 8 0 0 0 0 16zM11 7h2v2h-2V7zm0 4h2v6h-2v-6z"></path></svg> <?php echo $wo['group_profile']['about']?>
									</div>
								<?php } ?>
							</div>
						</div>
					</div>
					<div class="col-lg-2"></div>
				</div>
			<?php } else { ?>
				<div class="row tag_profile_row">
					<?php
						if (isset($_GET['type'])) {
							if ($_GET['type'] == 'members') {
								if ($show_list == true) {
									# code...
					?>
						<div class="col-md-12">
							<?php if ($show_list == true): ?>
								<div class="page-margin">
									<ul class="list-unstyled tag_page_nav">
										<li><a href="<?php echo Wo_SeoLink('index.php?link1=?link1=timeline&u=' . $wo['group_profile']['group_name'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>" class="btn-mat"><?php echo $wo['lang']['home'];?></a></li>
										<li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=members" class="btn-mat"><?php echo $wo['lang']['members'];?></a></li>
										<?php if ($wo['loggedin'] == true) { ?>
										<?php if (Wo_IsGroupJoined($wo['group_profile']['id']) === true) { ?>
											<li><a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=add_members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=add_members" class="btn-mat"><?php echo $wo['lang']['invite'];?></a></li>
										<?php } } ?>
									</ul>
								</div>
							<?php endif ?>
							<div class="page-margin wow_content wow_sett_content">
								<div class="valign wo_page_hdng">
									<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M16,13C15.71,13 15.38,13 15.03,13.05C16.19,13.89 17,15 17,16.5V19H23V16.5C23,14.17 18.33,13 16,13M8,13C5.67,13 1,14.17 1,16.5V19H15V16.5C15,14.17 10.33,13 8,13M8,11A3,3 0 0,0 11,8A3,3 0 0,0 8,5A3,3 0 0,0 5,8A3,3 0 0,0 8,11M16,11A3,3 0 0,0 19,8A3,3 0 0,0 16,5A3,3 0 0,0 13,8A3,3 0 0,0 16,11Z"></path></svg></span> <?php echo $wo['lang']['members']; ?>
								</div>
								<div class="row">
									<?php
										if (Wo_CountGroupMembers($wo['group_profile']['id']) == 0) {
											echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" height="512" viewBox="0 0 32 32" width="512"><path d="m26 32h-20c-3.314 0-6-2.686-6-6v-20c0-3.314 2.686-6 6-6h20c3.314 0 6 2.686 6 6v20c0 3.314-2.686 6-6 6z" fill="#ffe6e2"/><g fill="#fd907e"><circle cx="10.667" cy="14.917" r="1.333"/><path d="m12.447 17.183c-.673.507-1.113 1.32-1.113 2.233v.167h-2.834c-.273 0-.5-.227-.5-.5v-.333c0-1.013.82-1.833 1.833-1.833h1.667c.347 0 .673.1.947.266z"/><circle cx="21.333" cy="14.917" r="1.333"/><path d="m24 18.75v.333c0 .273-.227.5-.5.5h-2.833v-.167c0-.913-.44-1.727-1.113-2.233.273-.167.6-.267.947-.267h1.667c1.012.001 1.832.821 1.832 1.834z"/></g><circle cx="16" cy="14.583" fill="#fc573b" r="2"/><path d="m17.833 17.583h-3.667c-1.011 0-1.833.822-1.833 1.833v1c0 .276.224.5.5.5h6.333c.276 0 .5-.224.5-.5v-1c.001-1.01-.822-1.833-1.833-1.833z" fill="#fc573b"/></svg>' . $wo['lang']['no_members_found'] . '</div>';
										} else {
											foreach (Wo_GetGroupMembers($wo['group_profile']['id']) as $wo['UsersList']) {
												echo Wo_LoadPage('timeline/follow-list');
											}
										}
									?>
								</div>
								<div class="clear"></div>
							</div>
						</div>
					<?php } } else if ($_GET['type'] == 'add_members') { ?>
						<div class="col-md-12">
							<?php if ($show_list == true): ?>
								<div class="page-margin">
									<ul class="list-unstyled tag_page_nav">
										<li><a href="<?php echo Wo_SeoLink('index.php?link1=?link1=timeline&u=' . $wo['group_profile']['group_name'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>" class="btn-mat"><?php echo $wo['lang']['home'];?></a></li>
										<li><a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=members" class="btn-mat"><?php echo $wo['lang']['members'];?></a></li>
										<?php if ($wo['loggedin'] == true) { ?>
										<?php if (Wo_IsGroupJoined($wo['group_profile']['id']) === true) { ?>
											<li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=add_members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=add_members" class="btn-mat"><?php echo $wo['lang']['invite'];?></a></li>
										<?php } } ?>
									</ul>
								</div>
							<?php endif ?>
							<div class="page-margin wow_content wow_sett_content">
								<div class="valign wo_page_hdng">
									<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M13,13C11,13 7,14 7,16V18H19V16C19,14 15,13 13,13M19.62,13.16C20.45,13.88 21,14.82 21,16V18H24V16C24,14.46 21.63,13.5 19.62,13.16M13,11A3,3 0 0,0 16,8A3,3 0 0,0 13,5A3,3 0 0,0 10,8A3,3 0 0,0 13,11M18,11A3,3 0 0,0 21,8A3,3 0 0,0 18,5C17.68,5 17.37,5.05 17.08,5.14C17.65,5.95 18,6.94 18,8C18,9.06 17.65,10.04 17.08,10.85C17.37,10.95 17.68,11 18,11M8,10H5V7H3V10H0V12H3V15H5V12H8V10Z"></path></svg></span> <?php echo $wo['lang']['add_your_frineds']; ?>
								</div>
								<div class="row">
									<?php
										if (Wo_CountGroupsNotMember($wo['group_profile']['id']) == 0) {
											echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" height="512" viewBox="0 0 32 32" width="512"><path d="m26 32h-20c-3.314 0-6-2.686-6-6v-20c0-3.314 2.686-6 6-6h20c3.314 0 6 2.686 6 6v20c0 3.314-2.686 6-6 6z" fill="#ffe6e2"/><g fill="#fd907e"><circle cx="10.667" cy="14.917" r="1.333"/><path d="m12.447 17.183c-.673.507-1.113 1.32-1.113 2.233v.167h-2.834c-.273 0-.5-.227-.5-.5v-.333c0-1.013.82-1.833 1.833-1.833h1.667c.347 0 .673.1.947.266z"/><circle cx="21.333" cy="14.917" r="1.333"/><path d="m24 18.75v.333c0 .273-.227.5-.5.5h-2.833v-.167c0-.913-.44-1.727-1.113-2.233.273-.167.6-.267.947-.267h1.667c1.012.001 1.832.821 1.832 1.834z"/></g><circle cx="16" cy="14.583" fill="#fc573b" r="2"/><path d="m17.833 17.583h-3.667c-1.011 0-1.833.822-1.833 1.833v1c0 .276.224.5.5.5h6.333c.276 0 .5-.224.5-.5v-1c.001-1.01-.822-1.833-1.833-1.833z" fill="#fc573b"/></svg>' . $wo['lang']['added_all_friends'] . '</div>';
										} else {
											foreach (Wo_GetGroupsNotMember($wo['group_profile']['id']) as $wo['UsersList']) {
												echo Wo_LoadPage('group/add-list');
											}
										}
									?>
								</div>
								<div class="clear"></div>
							</div>
						</div>
					<?php } } else { ?>
						<?php if ($show_list == true): ?>
							<div class="col-md-12">
								<div class="page-margin">
									<ul class="list-unstyled tag_page_nav">
										<li class="active"><a href="<?php echo Wo_SeoLink('index.php?link1=?link1=timeline&u=' . $wo['group_profile']['group_name'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>" class="btn-mat"><?php echo $wo['lang']['home'];?></a></li>
										<li><a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=members" class="btn-mat"><?php echo $wo['lang']['members'];?></a></li>
										<?php if ($wo['loggedin'] == true) { ?>
										<?php if (Wo_IsGroupJoined($wo['group_profile']['id']) === true) { ?>
											<li><a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=add_members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=add_members" class="btn-mat"><?php echo $wo['lang']['invite'];?></a></li>
										<?php } } ?>
									</ul>
								</div>
							</div>
						<?php endif ?>
						<div class="col-lg-7 middlecol">
							<?php echo Wo_GetGroupPostPublisherBox($wo['group_profile']['id']); ?>
		
							<?php if ($wo['loggedin'] == true) { echo Wo_LoadPage('story/filter-by'); } ?>
		
							<div id="posts" data-story-group="<?php echo $wo['group_profile']['id'];?>">
								<div class="pinned-post-container">
									<?php
										$pinedstory = Wo_GetPinnedPost($wo['group_profile']['id'], 'group');
										if (count($pinedstory) == 1) {
											foreach ($pinedstory  as $wo['story']) {
												echo Wo_LoadPage('story/content');
											}
										}
									?>
								</div>
								<?php
									$stories = Wo_GetPosts(array('filter_by' => 'all', 'group_id' => $wo['group_profile']['id'],'placement' => 'multi_image_post')); 
									if (count($stories) == 0 && count($pinedstory) == 0) {
										echo Wo_LoadPage('story/group-no-stories');
									} else {
										foreach ($stories as $wo['story']) {
											echo Wo_LoadPage('story/content');
										}
									}
								?>
							</div>
							<?php if ($wo['loggedin'] == true && count($stories) > 0) {  ?>
								<div class="load-more pointer" id="load-more-posts" onclick="Wo_GetMorePosts();">
									<span class="btn btn-default text-center pointer"><span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"></path></svg></span> <?php echo $wo['lang']['load_more_posts']; ?><span>
								</div>
							<?php } ?>
							<div id="load-more-filter">
								<span class="filter-by-more hidden" data-filter-by="all"></span>
							</div>
						</div>
						<div class="col-lg-3 sidebar rightcol custom-fixed-side">
							<div class="page-margin wow_content p15 mt-0">
								<?php if($wo['loggedin'] == true) {  ?>
									<input type="text" class="search-for-posts tag_profile_search" onkeyup="Wo_SearchForPosts(this.value);" placeholder="<?php echo $wo['lang']['search_for_posts']; ?>"/>
								<?php } ?>
								<div class="event_info_blocks">
									<?php if ($wo['loggedin'] == true) { ?>
									<?php if (Wo_IsGroupJoined($wo['group_profile']['id']) === true) { ?>
										<div>
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M14 14.252v2.09A6 6 0 0 0 6 22l-2-.001a8 8 0 0 1 10-7.748zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6zm0-2c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm6 6v-3h2v3h3v2h-3v3h-2v-3h-3v-2h3z"></path></svg>
											<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=add_members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=add_members"><?php echo $wo['lang']['add_your_frineds']; ?></a>
										</div>
									<?php } } ?>
									<div><?php echo $group_icon; ?> <?php echo $group_privacy; ?></div>
									<?php if ($show_list == true): ?>
									<div>
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M9.55 11.5a2.25 2.25 0 1 1 0-4.5 2.25 2.25 0 0 1 0 4.5zm.45 8.248V16.4c0-.488.144-.937.404-1.338a6.473 6.473 0 0 0-5.033 1.417A8.012 8.012 0 0 0 10 19.749zM4.453 14.66A8.462 8.462 0 0 1 9.5 13c1.043 0 2.043.188 2.967.532.878-.343 1.925-.532 3.033-.532 1.66 0 3.185.424 4.206 1.156a8 8 0 1 0-15.253.504zm14.426 1.426C18.486 15.553 17.171 15 15.5 15c-2.006 0-3.5.797-3.5 1.4V20a7.996 7.996 0 0 0 6.88-3.914zM12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm3.5-9.5a2 2 0 1 1 0-4 2 2 0 0 1 0 4z"></path></svg> <a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=members"><?php echo Wo_CountGroupMembers($wo['group_profile']['id']);?> <?php echo $wo['lang']['members'];?></a>
										<?php if (Wo_IsGroupOnwer($wo['group_profile']['id'])) { ?>
											<span class="green">+<?php echo Wo_CountJoinedThisWeek($wo['group_profile']['id']); ?> <?php echo $wo['lang']['this_week']; ?></span>
										<?php } ?>
									</div>
									<?php endif ?>
									<div>
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M10.9 2.1l9.899 1.415 1.414 9.9-9.192 9.192a1 1 0 0 1-1.414 0l-9.9-9.9a1 1 0 0 1 0-1.414L10.9 2.1zm.707 2.122L3.828 12l8.486 8.485 7.778-7.778-1.06-7.425-7.425-1.06zm2.12 6.364a2 2 0 1 1 2.83-2.829 2 2 0 0 1-2.83 2.829z"></path></svg> <?php echo $wo['group_profile']['category']; ?>
									</div>
									<?php if (!empty($wo['group_profile']['group_sub_category'])) { ?>
										<div>
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" title="<?php echo $wo['lang']['sub_category']; ?>"><path fill="currentColor" d="M10.9 2.1l9.899 1.415 1.414 9.9-9.192 9.192a1 1 0 0 1-1.414 0l-9.9-9.9a1 1 0 0 1 0-1.414L10.9 2.1zm.707 2.122L3.828 12l8.486 8.485 7.778-7.778-1.06-7.425-7.425-1.06zm2.12 6.364a2 2 0 1 1 2.83-2.829 2 2 0 0 1-2.83 2.829z"></path></svg> <?php echo $wo['group_profile']['group_sub_category']; ?>
										</div>
									<?php } ?>
									<div>
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M20 22H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1zm-1-2V4H5v16h14zM8 7h8v2H8V7zm0 4h8v2H8v-2zm0 4h5v2H8v-2z"></path></svg> <?php echo Wo_CountGroupPosts($wo['group_profile']['id']);?> <?php echo $wo['lang']['posts']; ?>
									</div>
									<?php 
									$fields = Wo_GetCustomFields('group'); 
									if (!empty($fields)) {
										foreach ($fields as $key => $wo['field']) { 
											if (!empty($wo['group_profile']['fid_'.$wo['field']['id']])) {
												$text = $wo['group_profile']['fid_'.$wo['field']['id']];
												if ($wo['field']['type'] == 'selectbox') {
													 $options = @explode(',', $wo['field']['options']);
													foreach ($options as $key => $value) {
														if ($key + 1 == $wo['group_profile']['fid_'.$wo['field']['id']]) {
															$text = $options[$key];
														}
													}						
												}
									?>
										<div>
											<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="feather"><path fill="currentColor" d="M13.5,4A1.5,1.5 0 0,0 12,5.5A1.5,1.5 0 0,0 13.5,7A1.5,1.5 0 0,0 15,5.5A1.5,1.5 0 0,0 13.5,4M13.14,8.77C11.95,8.87 8.7,11.46 8.7,11.46C8.5,11.61 8.56,11.6 8.72,11.88C8.88,12.15 8.86,12.17 9.05,12.04C9.25,11.91 9.58,11.7 10.13,11.36C12.25,10 10.47,13.14 9.56,18.43C9.2,21.05 11.56,19.7 12.17,19.3C12.77,18.91 14.38,17.8 14.54,17.69C14.76,17.54 14.6,17.42 14.43,17.17C14.31,17 14.19,17.12 14.19,17.12C13.54,17.55 12.35,18.45 12.19,17.88C12,17.31 13.22,13.4 13.89,10.71C14,10.07 14.3,8.67 13.14,8.77Z"></path></svg> <?php echo $text; ?>
										</div>
									<?php } } } ?>
									<?php if(!empty($wo['group_profile']['about'])) {  ?>
										<div>
											<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-2a8 8 0 1 0 0-16 8 8 0 0 0 0 16zM11 7h2v2h-2V7zm0 4h2v6h-2v-6z"></path></svg> <?php echo $wo['group_profile']['about']?>
										</div>
									<?php } ?>
									<?php if ($wo['loggedin'] && !Wo_IsAdmin() && $wo['user']['id'] != $wo['group_profile']['user_id'] && !Wo_IsAdmin($wo['group_profile']['user_id'])): ?>
									<?php if (!Wo_IsReportExists($wo['group_profile']['id'],'group')): ?>
										<div id="report_status" class="pointer" onclick="$('#report_group').modal('show');">
											<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M4 17v5H2V3h19.138a.5.5 0 0 1 .435.748L18 10l3.573 6.252a.5.5 0 0 1-.435.748H4zM4 5v10h14.554l-2.858-5 2.858-5H4z"></path></svg> <?php echo $wo['lang']['report_group']; ?>
										</div>
									<?php else: ?>
										<div id="report_status" class="pointer" onclick="Wo_ReportGroup(<?php echo $wo['group_profile']['id']; ?>,false);">
											<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M4 17v5H2V3h19.138a.5.5 0 0 1 .435.748L18 10l3.573 6.252a.5.5 0 0 1-.435.748H4zM4 5v10h14.554l-2.858-5 2.858-5H4z"></path></svg> <?php echo $wo['lang']['unreport']; ?>
										</div>
									<?php endif; ?>
									<?php endif; ?>
								</div>
							</div>
							<?php if (Wo_IsMobile() == false) { ?>
							<?php if($wo['loggedin'] == true) {  ?>
							<?php
								$groups = Wo_GroupSug(1);
								if (count($groups) > 0) {
							?>
								<div class="page-margin wow_content wow_sett_content tag_profile_widget_hide" id="sidebar-group-list-container">
									<div class="valign wo_page_hdng">
										<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z"></path></svg></span> <?php echo $wo['lang']['suggested_groups']; ?>
									</div>
									<div class="sidebar-group-may-know-container tag_group_main_sugg_grp">
										<?php 
											foreach ($groups as $wo['GroupList']) {
											$wo['GroupList']['name'] = substr($wo['GroupList']['name'],0,20);
											echo Wo_LoadPage('sidebar/sidebar-group-list');
										} 
										?>
									</div>
									<div class="clear"></div>
								</div>
							<?php } ?>
							<?php } ?>
							<?php } ?>
							<?php 
							$sidebar_ad = Wo_GetAd('sidebar', false);
							if (!empty($sidebar_ad)) {?>
								<div class="sidebar-ad">
									<?php echo $sidebar_ad; ?>
								</div>
							<?php } ?>
						</div>
					<?php } ?>
				</div>
			<?php } ?>
		</div>
	</div>
</div>

<div class="modal fade" id="report_group" role="dialog">
	<div class="modal-dialog modal-md wow_mat_mdl">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><?php echo $wo['lang']['report_group'] ?></h4>
			</div>
			<div class="modal-body">
				<label class="tag_field">
					<textarea placeholder=" " dir="auto" rows="5" id="report-group-text-<?php echo $wo['group_profile']['id']; ?>"></textarea>
					<span><?php echo $wo['lang']['reason'] ?></span>
				</label>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-mat disable_btn" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['cancel']; ?></button>
				<button type="button" class="btn btn-main btn-mat disable_btn" id="report-group-button" onclick="Wo_ReportGroup(<?php echo $wo['group_profile']['id']; ?>,true)"><?php echo $wo['lang']['send']; ?></button>
			</div>
		</div>
	</div>
</div>

<script>
jQuery(document).ready(function() {jQuery('.custom-fixed-side').theiaStickySidebar({additionalMarginTop: 15});});

$(function () {
  $('form.profile-avatar-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_group_avatar_picture',

    beforeSend: function () {
      $('.user-avatar-uploading-container').fadeIn(200);
    },
    success: function (data) {
      if(data.status == 200) {
        $('[id^=group-avatar-image]').attr("src", data.img);
      }
      $('.user-avatar-uploading-container').fadeOut(200);
    }
  });

  $('form.profile-cover-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_group_cover_picture',

    beforeSend: function () {
      $('.user-cover-uploading-progress').fadeIn(200);
    },
    success: function (data) {
      if(data.status == 200) {
        $('[id^=cover-image]').attr("src", data.img);
      }
      $('.user-cover-uploading-progress').fadeOut(200);
    }
  });
});

function Wo_UpdateProfileAvatar() {
  $("form.profile-avatar-changer").submit();
}

function Wo_UpdateProfileCover() {
  $("form.profile-cover-changer").submit();
}

function Wo_ReportGroup(id = false,report = true){
    var report_text = $("#report-group-text-<?php echo $wo['group_profile']['id']; ?>").val();
    if (!id) {return false;}
    else if(report == true){
      if (!report_text) {return false;}  
    }
    $('#report_group').find('.disable_btn').attr('disabled','disabled');
    $.ajax({
        url: Wo_Ajax_Requests_File() + '?f=reports&s=report_group',
        type: 'POST',
        dataType: 'json',
        data: {text:report_text,group:id}
    })
    .done(function(data) {
        if(data.status == 200 && data.code == 0){
            $('#report_status').replaceWith('\
                <div id="report_status" class="list-group-item pointer" onclick="$(\'#report_group\').modal(\'show\');">\
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M4 17v5H2V3h19.138a.5.5 0 0 1 .435.748L18 10l3.573 6.252a.5.5 0 0 1-.435.748H4zM4 5v10h14.554l-2.858-5 2.858-5H4z"></path></svg> <?php echo $wo['lang']['report_group']; ?>\
                </div>');
        }

        else if (data.status == 200 && data.code == 1) {
            $("#report-group-text-<?php echo $wo['group_profile']['id']; ?>").val('');
            $("#report_group").modal('hide');
            $('#report_status').replaceWith('\
                <div id="report_status" class="list-group-item pointer" onclick="Wo_ReportGroup(<?php echo $wo['group_profile']['id']; ?>,false);">\
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M4 17v5H2V3h19.138a.5.5 0 0 1 .435.748L18 10l3.573 6.252a.5.5 0 0 1-.435.748H4zM4 5v10h14.554l-2.858-5 2.858-5H4z"></path></svg> <?php echo $wo['lang']['unreport']; ?>\
                </div>');
        }
        $('#report_group').find('.disable_btn').removeAttr("disabled");
    })
    .fail(function() {
        console.log("error");
    })
}
</script>