<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bbcode/jquery.bbcode.js"></script>
<link rel="stylesheet" href="<?php echo $wo['config']['theme_url'];?>/javascript/bbcode/jquery.bbcode.css" media="all">
<?php 
$forum_class = 'search-forums';
if (!empty($_GET['fid'])) {
	$forum_class = 'search-forum-threads';
}
if ($_GET['link1'] == 'showthread') {
	$forum_class = 'forum-messages-search';
}

 ?>
<div class="page-margin" id="forum-cont">
	<div class="container">
		<h2 class="tag_page_title m5"><?php echo $wo['lang']['forum']; ?></h2>
		<ul class="list-unstyled tag_page_nav">
			<li class="<?php if ($wo['active'] == 'forums') echo 'active'; ?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=forum');?>" data-ajax="?link1=forum"><?php echo $wo['lang']['browse_forum']; ?></a></li>
			<li class="<?php if ($wo['active'] == 'members') echo 'active'; ?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=forum-members');?>" data-ajax="?link1=forum-members"><?php echo $wo['lang']['members']; ?></a></li>
			<li class="separate <?php if ($wo['active'] == 'search') echo 'active'; ?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=forum-search');?>" data-ajax="?link1=forum-search"><?php echo $wo['lang']['search']; ?></a></li>
			<li class="<?php if ($_GET['link1'] == 'mythreads') echo 'active'; ?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=mythreads');?>" data-ajax="?link1=mythreads"><?php echo $wo['lang']['my_threads']; ?></a></li>
			<li class="<?php if ($_GET['link1'] == 'mymessages') echo 'active'; ?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=mymessages');?>" data-ajax="?link1=mymessages"><?php echo $wo['lang']['my']; ?> <?php echo $wo['lang']['replies']; ?></a></li>
		</ul>
		<div class="tab-content" id="tab-content">