<div class="cool-style-album col-xs-6 col-sm-6 col-lg-4" id="album_<?php echo $wo['album']['id'];?>">
	<div class="wow_content tag_albums">
		<div class="avatar">
			<a href="<?php echo $wo['album']['url'];?>" data-ajax="?link1=post&id=<?php echo $wo['album']['id'];?>">
				<?php if ($wo['album']['blur'] == 1) { ?>
					<img src="<?php echo $wo['album']['first_image'];?>" alt="<?php echo $wo['album']['first_image']; ?> Picture" class="image_blur"/>
		      	<?php }else{ ?>
		      		<img src="<?php echo $wo['album']['first_image'];?>" alt="<?php echo $wo['album']['first_image']; ?> Picture" />
		      	<?php } ?>
			</a>
			<div class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"></path></svg></a>
				<ul class="dropdown-menu dropdown-menu-right tag_create_menu clearfix" role="menu">
					<li>
						<a href="<?php echo Wo_SeoLink('index.php?link1=create-album&album=' . $wo['album']['id']);?>">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M21 15v3h3v2h-3v3h-2v-3h-3v-2h3v-3h2zm.008-12c.548 0 .992.445.992.993v9.349A5.99 5.99 0 0 0 20 13V5H4l.001 14 9.292-9.293a.999.999 0 0 1 1.32-.084l.093.085 3.546 3.55a6.003 6.003 0 0 0-3.91 7.743L2.992 21A.993.993 0 0 1 2 20.007V3.993A1 1 0 0 1 2.992 3h18.016zM8 7a2 2 0 1 1 0 4 2 2 0 0 1 0-4z"></path><path fill="currentColor" d="M21 15v3h3v2h-3v3h-2v-3h-3v-2h3v-3h2zm.008-12c.548 0 .992.445.992.993V13h-2V5H4v13.999L14 9l3 3v2.829l-3-3L6.827 19H14v2H2.992A.993.993 0 0 1 2 20.007V3.993A1 1 0 0 1 2.992 3h18.016zM8 7a2 2 0 1 1 0 4 2 2 0 0 1 0-4z"></path></svg> <?php echo $wo['lang']['add_photos'];?>
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="album-name">
			<h4 class="truncate"><a href="<?php echo $wo['album']['url'];?>" data-ajax="?link1=post&id=<?php echo $wo['album']['id'];?>"><?php echo $wo['album']['album_name']; ?></a></h4>
			<p><?php echo Wo_Time_Elapsed_String($wo['album']['time']); ?></p>
			<span class="alb_count" title="<?php echo $wo['lang']['photos']; ?>"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1,3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z" /></svg> <?php echo Wo_CountAlbumImages($wo['album']['id']);?></span>
		</div>
	</div>
</div>