<span class="user-follow-request-<?php echo $wo['follow']['user_id'];?>">
	<span class="accept-btns">
		<button type="button" onclick="Wo_AcceptFollowRequest(<?php echo $wo['follow']['user_id'];?>)" class="btn btn-default btn-mat">
			<svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M9 16.17L5.53 12.7c-.39-.39-1.02-.39-1.41 0-.39.39-.39 1.02 0 1.41l4.18 4.18c.39.39 1.02.39 1.41 0L20.29 7.71c.39-.39.39-1.02 0-1.41-.39-.39-1.02-.39-1.41 0L9 16.17z"/></svg>
			<span class="button-text"> <?php echo $wo['lang']['accept'];?></span>
		</button>
	</span>
</span>