<?php 
	function Wo_GetRandProducts($limit) {
		global $sqlConnect, $wo;
		$data = array();
		$query  = mysqli_query($sqlConnect, "SELECT * FROM  " . T_PRODUCTS . "  
											 ORDER BY RAND() DESC LIMIT $limit");
		while ($fetched_data = mysqli_fetch_assoc($query)) {
			$products           = Wo_GetProduct($fetched_data['id']);
			$data[]             = $products;
		}
		return $data;
	}
?>

<div class="page-margin">
	<div class="container">
		<div class="row">
			<div class="col-lg-7 middlecol prod_full_size">
				<?php echo Wo_LoadPage('story/content'); ?>
				<?php if (Wo_IsMobile() == false) { ?>
				<?php if (!empty($wo['story']['product_id'])) { ?>
					<div class="tag_post_more_prods">
						<h3><?php echo $wo['lang']['more_like_this'];?></h3>
						<div class="row">
							<?php 
								$products = Wo_GetRandProducts(8);
								foreach ($products as $key => $wo['product']) {
									echo Wo_LoadPage('products/post-products-list'); 
								}
							?>
						</div>
					</div>
				<?php } } ?>
			</div>
			<?php 
			if($wo['loggedin'] == true) {
				echo Wo_LoadPage('sidebar/content');
			} else {
				echo Wo_LoadPage('sidebar/guest');
			}
			?>
		</div>
   </div>
</div>

<?php if (!empty($_GET['ref']) && is_numeric($_GET['ref']) && $_GET['ref'] > 0) { ?>
<script type="text/javascript">
	$.fn.scrollTo = function( target, options, callback ){
		if(typeof options == 'function' && arguments.length == 2){ callback = options; options = target; }
		var settings = $.extend({
			scrollTarget  : target,
			offsetTop     : 75,
			duration      : 500,
			easing        : 'swing'
		}, options);
		return this.each(function(){
			var scrollPane = $(this);
			var scrollTarget = (typeof settings.scrollTarget == "number") ? settings.scrollTarget : $(settings.scrollTarget);
			var scrollY = (typeof scrollTarget == "number") ? scrollTarget : scrollTarget.offset().top + scrollPane.scrollTop() - parseInt(settings.offsetTop);
			scrollPane.animate({scrollTop : scrollY }, parseInt(settings.duration), settings.easing, function(){
				if (typeof callback == 'function') { callback.call(this); }
			});
		});
	}

	$(function () {
		var comment_reply = $("#comment_<?php echo $_GET['ref']?>");
		Wo_ViewMoreReplies(<?php echo $_GET['ref']?>);
		setTimeout(function(){
			if (comment_reply.length) {
				$('body').scrollTo("#comment_<?php echo $_GET['ref']?>");
				$("#comment_<?php echo $_GET['ref']?>").addClass("light").delay(1000).queue(function(next){
					$(this).removeClass("light");
					next();
				});
			}
		}, 500);
	});
</script>
<?php } ?>