<div class="dropdown recipient-chat-user" id="online_{{chat_list_user_id}}">
	<div class="pointer user-info" data-toggle="dropdown" data-display="static" role="button" onclick="Wo_OpenChatTab({{chat_list_user_id}});">
		<img src="{{chat_list_avatar}}" alt="{{chat_list_name}}" />
		<span class="new-message-alert {{#if is_message_count_zero}}  hidden {{/if}}">{{message_count_per_user}}</span>
		<svg xmlns="http://www.w3.org/2000/svg" width="9" height="9" viewBox="0 0 24 24"><path fill="#60d465" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>
		<span class="valign chat-loading-icon"></span>
	</div>
	<ul class="dropdown-menu" role="menu">
		<div class="valign">
			<img src="{{chat_list_avatar}}" alt="{{chat_list_name}}" />
			<div>
				<div class="chat-user-text" id="chat-tab-id">{{chat_list_name}}</div>
				<small>{{lang_online}}</small>
			</div>
		</div>
	</ul>
</div>
<div class="clear"></div>