<style>
.tag_content.opacity_start {opacity: 1;pointer-events: auto;}
</style>
<?php
$user_id            = $wo['user']['user_id'];
$wo['is_admin']     = Wo_IsAdmin();
$wo['is_moderoter'] = Wo_IsModerator();

$wo['setting']['admin'] = false;
if (isset($_GET['user']) && !empty($_GET['user']) && ($wo['is_admin'] === true || $wo['is_moderoter'] === true)) {
    if (Wo_UserExists($_GET['user']) === false) {
        header("Location: " . $wo['config']['site_url']);
        exit();
    }
    $user_id                = Wo_UserIdFromUsername($_GET['user']);
    $wo['setting']['admin'] = true;
}
$wo['setting'] = Wo_UserData($user_id);
if ($wo['is_moderoter']) {
  if ($wo['setting']['admin'] == 1) {
       header("Location: " . $wo['config']['site_url']);
       exit();
  }
}
$wo['setting']['fileds'] = Wo_UserFieldsData($user_id);
$wo['setting_page'] = 'general-setting';
$pages_array = array(
   'general-setting',
   'profile-setting',
   'privacy-setting',
   'change-password-setting',
   'social-links',
   'design-setting',
   'avatar-setting',
   'email-setting',
   'verification',
   'blocked-users',
   'transaction_log',
   'my_points',
   'manage-sessions',
   'notifications-settings',
   'two-factor',
   'my_info',
   'invitation_links'
);
if ($wo['setting']['user_id'] == $wo['user']['user_id']) {
  $pages_array = array(
   'general-setting',
   'profile-setting',
   'privacy-setting',
   'change-password-setting',
   'social-links',
   'delete-account',
   'design-setting',
   'avatar-setting',
   'email-setting',
   'verification',
   'blocked-users',
   'transaction_log',
   'my_points',
   'manage-sessions',
   'notifications-settings',
   'two-factor',
   'my_info',
   'invitation_links'
   );
}
if ($wo['config']['affiliate_system'] == 1) {
  $pages_array[] = 'affiliates';
}
if ($wo['config']['affiliate_system'] == 1 || $wo['config']['point_allow_withdrawal'] == 1 || $wo['config']['funding_system'] == 1) {
	$pages_array[] = 'payments';
}
if (!empty($_GET['page'])) {
   if (in_array($_GET['page'], $pages_array)) {
      $wo['setting_page'] = $_GET['page'];
   }
   if ($wo['config']['deleteAccount'] != 1 && $wo['setting_page'] == 'delete-account') {
   	$wo['setting_page'] = 'general-setting';
   }
}
$wo['user_setting'] = '';
if (!empty($_GET['user'])) {
    $wo['user_setting'] = 'user=' . $_GET['user']. '&';
}
if ($wo['setting_page'] == 'invitation_links') {
	$wo['available_links'] = Wo_GetAvailableLinks($wo['setting']['user_id']);
	if ($wo['config']['user_links_limit'] > 0) {
		$wo['generated_links'] = $wo['config']['user_links_limit'] - $wo['available_links'];
	}
	else{
		$wo['generated_links'] = Wo_GetGeneratedLinks($wo['setting']['user_id']);
	}
	$wo['used_links'] = Wo_GetUsedLinks($wo['setting']['user_id']);
}
?>

<div class="page-margin tag_hdr_top_sett">
	<div class="container">
		<div class="row">
			<div class="col-md-12"><?php echo Wo_LoadPage('setting/user-setting-sidebar');?></div>
		</div>
		<div class="row">
			<div class="col-lg-1"></div>
			<div class="col-lg-10 tag_sett_page tag_mobi_sett_page" id="tag_sett_right_prt"><?php echo Wo_LoadPage("setting/" . $wo['setting_page']); ?></div>
			<div class="col-lg-1"></div>
		</div>
	</div>
</div>

<div class="modal fade" id="verify_email_phone" role="dialog">
	<div class="modal-dialog wow_mat_mdl modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="verify_email_phone_title">
					<?php 
						if ($wo['config']['sms_or_email'] == 'mail') {
							echo $wo['lang']['confirmation_message_email_sent'];
						}
						elseif ($wo['config']['sms_or_email'] == 'sms') {
							echo $wo['lang']['confirmation_message_sent'];
						}
					?>
				</h4>
			</div>
			<form id="verify_email_phone_form" class="verify_email_phone_form" method="POST">
				<div class="modal-body">
					<div id="verify_email_phone_form_alert"></div>
					<p id="verify_email_phone_desc">
						<?php 
							if ($wo['config']['sms_or_email'] == 'mail') {
								echo $wo['lang']['confirmation_email_text'];
							}
							elseif ($wo['config']['sms_or_email'] == 'sms') {
								echo $wo['lang']['confirmation_message_text'];
							}
						?>
					</p>
					<div class="form-group verfy_sett_email_phone">
						<input type="text" class="form-control" name="code" placeholder="<?php echo $wo['lang']['confirmation_code']; ?>">
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-mat disable_btn" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['cancel'] ?></button>
					<button id="verify_email_phone_form_btn" type="submit" class="btn btn-main btn-mat disable_btn"><?php echo $wo['lang']['verify']; ?></button>
				</div>
			</form>
		</div>
	</div>
</div>