<h2 class="tag_page_title"><button type="button" class="btn setting_navigation" onclick="$('.tag_sett_sidebar').fadeIn(50);$('#tag_sett_right_prt').fadeOut(50);"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z" fill="currentColor"></path></svg></button> <?php echo $wo['lang']['manage_sessions']; ?></h2>
<div class="wow_sett_content wow_content p20">
	<a href="javascript:void();" class="btn btn-danger btn-mat mb-15" id="upgrade-button" onclick="Wo_RemoveAllSessions();"><?php echo $wo['lang']['remove_all_sessions'];?></a>
	<div class="active_sessions">
		<div class="table-responsive">
			<?php
				$get_sessions = Wo_GetAllSessionsFromUserID($wo['setting']['user_id']);
				if (count($get_sessions) > 0) {
					foreach ($get_sessions as $wo['key'] => $wo['session']) {
						echo Wo_LoadPage('setting/includes/sessions');
					}
				}
			?>
		</div>
	</div>
</div>

<script type="text/javascript">
function logOutSession(id) {
	if (!confirm('Are you sure you want to log out from this device?')) {
		return false;
	}
	$('#session_' + id).remove();
	$.post(Wo_Ajax_Requests_File() + '?f=delete_s', {id: id}, function () {
		Wo_IsLogged();
	});
}
function Wo_RemoveAllSessions() {
	if (!confirm('Are you sure you want to log out from this device and all devices ?')) {
		return false;
	}
	$.post(Wo_Ajax_Requests_File() + '?f=delete_all_sessions', function () {
		Wo_IsLogged();
	});
}
</script>