<h2 class="tag_page_title"><button type="button" class="btn setting_navigation" onclick="$('.tag_sett_sidebar').fadeIn(50);$('#tag_sett_right_prt').fadeOut(50);"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z" fill="currentColor"></path></svg></button> <?php echo $wo['lang']['privacy_setting']; ?></h2>
<div class="wow_sett_content wow_content p20">
	<form class="form-horizontal setting-privacy-form wo_settings_page" method="post">
		<div class="setting-privacy-alert setting-update-alert"></div>
		
		<label class="tag_field">
			<select id="chat_status" name="status">
				<?php 
					$selected_chat_status_yes   = ($wo['setting']['status'] == 1)   ? ' selected' : '';
					$selected_chat_status_no    = ($wo['setting']['status'] == 0)   ? ' selected' : '';
				?>
				<option value="0" <?php echo $selected_chat_status_no; ?>><?php echo $wo['lang']['online']; ?></option>
				<option value="1" <?php echo $selected_chat_status_yes; ?>><?php echo $wo['lang']['offline']; ?></option>
			</select>
			<span><?php echo $wo['lang']['status']; ?></span>
		</label>
		<?php if ($wo['config']['connectivitySystem'] == 0) { ?>
			<label class="tag_field">
				<select id="follow_privacy" name="follow_privacy">
					<?php 
						$selected_followp_everyone   = ($wo['setting']['follow_privacy'] == 0)   ? ' selected' : '';
						$selected_followp_following  = ($wo['setting']['follow_privacy'] == 1)   ? ' selected' : '';
					?>
					<option value="0" <?php echo $selected_followp_everyone; ?>><?php echo $wo['lang']['everyone']; ?></option>
					<option value="1" <?php echo $selected_followp_following; ?>><?php  echo $wo['lang']['people_i_follow']; ?></option>
				</select>
				<span><?php echo $wo['lang']['follow_privacy_label']; ?></span>
			</label>
		<?php } ?>
		<label class="tag_field">
			<select id="message_privacy" name="message_privacy">
				<?php 
					$selected_meesageP_everyone   = ($wo['setting']['message_privacy'] == 0)   ? ' selected' : '';
					$selected_meesageP_following  = ($wo['setting']['message_privacy'] == 1)   ? ' selected' : '';
					$selected_meesageP_nobody  = ($wo['setting']['message_privacy'] == 2)   ? ' selected' : '';
				?>
				<option value="0" <?php echo $selected_meesageP_everyone; ?> ><?php echo $wo['lang']['everyone']; ?></option>
				<option value="1" <?php echo $selected_meesageP_following; ?> >
					<?php 
					if ($wo['config']['connectivitySystem'] == 1) {
						echo $wo['lang']['my_friends'];
					} else {
						echo $wo['lang']['people_i_follow'];
					}
					?>
				</option>
				<option value="2" <?php echo $selected_meesageP_nobody; ?> ><?php echo $wo['lang']['no_body']; ?></option>
			</select>
			<span><?php echo $wo['lang']['message_privacy_label']; ?></span>
		</label>
		<label class="tag_field">
			<select id="friend_privacy" name="friend_privacy">
				<?php 
					$selected_friendP_everyone    = ($wo['setting']['friend_privacy'] == 0)   ? ' selected' : '';
					$selected_friendP_following   = ($wo['setting']['friend_privacy'] == 1)   ? ' selected' : '';
					$selected_friendP_followingme = ($wo['setting']['friend_privacy'] == 2)   ? ' selected' : '';
					$selected_friendP_no_one      = ($wo['setting']['friend_privacy'] == 3)   ? ' selected' : '';
				?>
				<option value="0" <?php echo $selected_friendP_everyone; ?> ><?php echo $wo['lang']['everyone']; ?></option>
				<option value="1" <?php echo $selected_friendP_following; ?> ><?php echo $wo['lang']['people_i_follow'];?></option>
				<option value="2" <?php echo $selected_friendP_followingme; ?> ><?php echo $wo['lang']['people_follow_me'];?></option>
				<option value="3" <?php echo $selected_friendP_no_one; ?> ><?php echo $wo['lang']['no_body'];?></option>
			</select>
			<span><?php echo $wo['lang']['friend_privacy']; ?></span>
		</label>
		<label class="tag_field">
			<select id="post_privacy" name="post_privacy">
				<?php 
					$selected_postp_everyone   = ($wo['setting']['post_privacy'] == "everyone")   ? ' selected' : '';
					$selected_postp_following  = ($wo['setting']['post_privacy'] == "ifollow")     ? ' selected' : '';
					$selected_postp_none       = ($wo['setting']['post_privacy'] == "nobody")      ? ' selected'  : '';
				?>
				<option value="everyone" <?php echo $selected_postp_everyone; ?>><?php echo $wo['lang']['everyone']; ?></option>
				<option value="ifollow" <?php echo $selected_postp_following; ?>>
					<?php 
					if ($wo['config']['connectivitySystem'] == 1) {
						echo $wo['lang']['my_friends'];
					} else {
						echo $wo['lang']['people_i_follow'];
					}
					?>
				</option>
				<option value="nobody" <?php echo $selected_postp_none; ?>><?php echo $wo['lang']['no_body']; ?></option>
			</select>
			<span><?php echo $wo['lang']['timeline_post_privacy_label']; ?></span>
		</label>
		<label class="tag_field">
			<select id="birth_privacy" name="birth_privacy">
				<?php 
					$selected_birth_privacy_everyone   = ($wo['setting']['birth_privacy'] == 0)   ? ' selected' : '';
					$selected_birth_privacy_following  = ($wo['setting']['birth_privacy'] == 1)     ? ' selected' : '';
					$selected_birth_privacy_none       = ($wo['setting']['birth_privacy'] == 2)      ? ' selected'  : '';
				?>
				<option value="0" <?php echo $selected_birth_privacy_everyone; ?>><?php echo $wo['lang']['everyone']; ?></option>
				<option value="1" <?php echo $selected_birth_privacy_following; ?>>
					<?php 
					if ($wo['config']['connectivitySystem'] == 1) {
						echo $wo['lang']['my_friends'];
					} else {
						echo $wo['lang']['people_i_follow'];
					}
					?>
				</option>
				<option value="2" <?php echo $selected_birth_privacy_none; ?>><?php echo $wo['lang']['no_body']; ?></option>
			</select>
			<span><?php echo $wo['lang']['timeline_birthday_label']; ?></span>
		</label>
		<?php if($wo['config']['connectivitySystem'] == 0) { ?>
			<label class="tag_field">
				<select id="confirm_followers" name="confirm_followers">
					<?php 
						$selected_confirm_followers_no   = ($wo['setting']['confirm_followers'] == 0)   ? ' selected' : '';
						$selected_confirm_followers_yes  = ($wo['setting']['confirm_followers'] == 1)   ? ' selected' : '';
					?>
					<option value="0" <?php echo $selected_confirm_followers_no; ?>><?php echo $wo['lang']['no']; ?></option>
					<option value="1" <?php echo $selected_confirm_followers_yes; ?>><?php echo $wo['lang']['yes']; ?></option>
				</select>
				<span><?php echo $wo['lang']['confirm_request_privacy_label']; ?></span>
			</label>
		<?php } ?>
		<?php
			$profileVisits = 0;
			if ($wo['config']['pro'] == 1) {
				if ($wo['setting']['is_pro'] == 1 && in_array($wo['setting']['pro_type'], array_keys($wo['pro_packages_types'])) && $wo['pro_packages'][$wo['pro_packages_types'][$wo['setting']['pro_type']]]['profile_visitors'] == 1) {
				$profileVisits = 1;
				}
			} else {
				$profileVisits = 1;
			}
		?>
		<?php if ($profileVisits == 1) { ?>
			<?php if($wo['config']['profileVisit'] == 1) { ?>
				<label class="tag_field">
					<select id="visit_privacy" name="visit_privacy">
						<?php 
							$selected_visit_privacy_yes   = ($wo['setting']['visit_privacy'] == 0)   ? ' selected' : '';
							$selected_visit_privacy_no    = ($wo['setting']['visit_privacy'] == 1)   ? ' selected' : '';
						?>
						<option value="1" <?php echo $selected_visit_privacy_no; ?>><?php echo $wo['lang']['no']; ?></option>
						<option value="0" <?php echo $selected_visit_privacy_yes; ?>><?php echo $wo['lang']['yes']; ?></option>
					</select>
					<span><?php echo $wo['lang']['profile_visit_notification_p']; ?></span>
				</label>
				<div class="help-block"><?php echo $wo['lang']['profile_visit_notification_help']; ?></div>
			<?php } ?>
			<?php if($wo['config']['user_lastseen'] == 1 && in_array($wo['setting']['pro_type'], array_keys($wo['pro_packages_types'])) && $wo['pro_packages'][$wo['pro_packages_types'][$wo['setting']['pro_type']]]['last_seen'] == 1) { ?>
				<label class="tag_field">
					<select id="showlastseen" name="showlastseen">
						<?php 
							$selected_lastseen_yes   = ($wo['setting']['showlastseen'] == 1)   ? ' selected' : '';
							$selected_lastseen_no    = ($wo['setting']['showlastseen'] == 0)   ? ' selected' : '';
						?>
						<option value="0" <?php echo $selected_lastseen_no; ?>><?php echo $wo['lang']['no']; ?></option>
						<option value="1" <?php echo $selected_lastseen_yes; ?>><?php echo $wo['lang']['yes']; ?></option>
					</select>
					<span><?php echo $wo['lang']['lastseen_privacy_label']; ?></span>
				</label>
				<div class="help-block"><?php echo $wo['lang']['showlastseen_help']; ?></div>
			<?php } ?>
		<?php } ?>
		<label class="tag_field">
			<select id="show_activities_privacy" name="show_activities_privacy">
				<?php 
					$selected_activities_yes   = ($wo['setting']['show_activities_privacy'] == 1)   ? ' selected' : '';
					$selected_activities_no    = ($wo['setting']['show_activities_privacy'] == 0)   ? ' selected' : '';
				?>
				<option value="0" <?php echo $selected_activities_no; ?>><?php echo $wo['lang']['no']; ?></option>
				<option value="1" <?php echo $selected_activities_yes; ?>><?php echo $wo['lang']['yes']; ?></option>
			</select>
			<span><?php echo $wo['lang']['activities_privacy_label']; ?></span>
		</label>
		<label class="tag_field">
			<select id="share_my_location" name="share_my_location">
				<?php 
					$selected_share_my_location_yes   = ($wo['setting']['share_my_location'] == 1)   ? ' selected' : '';
					$selected_share_my_location_no    = ($wo['setting']['share_my_location'] == 0)   ? ' selected' : '';
				?>
				<option value="1" <?php echo $selected_share_my_location_yes; ?>><?php echo $wo['lang']['yes']; ?></option>
				<option value="0" <?php echo $selected_share_my_location_no; ?>><?php echo $wo['lang']['no']; ?></option>
			</select>
			<span><?php echo $wo['lang']['share_my_location']; ?></span>
		</label>
		<label class="tag_field">
			<select id="share_my_data" name="share_my_data">
				<?php 
					$selected_share_my_data_yes   = ($wo['setting']['share_my_data'] == 1)   ? ' selected' : '';
					$selected_share_my_data_no    = ($wo['setting']['share_my_data'] == 0)   ? ' selected' : '';
				?>
				<option value="1" <?php echo $selected_share_my_data_yes; ?>><?php echo $wo['lang']['yes']; ?></option>
				<option value="0" <?php echo $selected_share_my_data_no; ?>><?php echo $wo['lang']['no']; ?></option>
			</select>
			<span><?php echo $wo['lang']['index_my_page_privacy']; ?></span>
		</label>

		<div class="text-center">
			<button type="submit" class="btn btn-main btn-mat btn-mat-raised disable_btn"><?php echo $wo['lang']['save']; ?></button>
		</div>

		<input type="hidden" name="user_id" value="<?php echo $wo['setting']['user_id'];?>">
		<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
	</form>
</div>

<script type="text/javascript">
$(function() {
  $('form.setting-privacy-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_privacy_settings',
    beforeSend: function() {
      $('.wo_settings_page').find('.disable_btn').attr('disabled','disabled');
    },
    success: function(data) {
      scrollToTop();
      if (data.status == 200) {
        $('.setting-privacy-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          $(this).delay(2500).slideUp(500, function() {
            $(this).remove();
          });
        });
      } 
      $('.wo_settings_page').find('.disable_btn').removeAttr("disabled");
    }
  });
});
</script>