<?php 
if (!empty($wo['story']['parent_id'])) {
	$wo['story'] = $wo['post_shared_from'];
}
$is_voted = false;
if ($wo['loggedin'] == true) {
	$is_voted = Wo_IsPostVoted($wo['story']['id'], $wo['user']['user_id']); 
}
?>
<div class="options" data-vote='<?php echo ($is_voted) ? 'true' : 'false'?>'>
	<?php foreach ($wo['story']['options'] as $key => $value):
	$is_option_voted = false;
    if ($wo['loggedin'] == true) {
    	$is_option_voted = Wo_IsOptionVoted($value['id'], $wo['user']['user_id']);
    } 
	?>
		<div id="option-<?php echo $value['id']?>" class="wo_votes <?php echo ($is_option_voted) ? 'active':'';?> <?php echo ($is_voted) ? 'active_all' : ''?>" onclick="Wo_VoteUp(<?php echo $value['id']?>);" data-post-id="<?php echo $wo['current_post']['id'];?>">
			<div class="poll-option"><span class="truncate"><?php echo $value['text'];?></span></div>
			<div class="result-bar-parent <?php echo ($is_voted) ? '' : 'hidden'?>">
				<div class="result-bar" style="width:<?php echo $value['percentage'];?>"><?php echo ($value['percentage_num'] > 0 && $is_voted) ? ' ' : '';?></div>
			</div>
			<div class="answer-vote <?php echo ($is_voted) ? '' : 'hidden'?>"><?php echo ($is_voted) ? $value['percentage']:''?></div>
		</div>
	<?php endforeach ?>
	<div class="total-votes"><span id="total-votes"><?php echo $value['all'];?></span> <?php echo $wo['lang']['total_votes'] ?></div>
</div>
<?php $wo['story'] = $wo['current_post']; ?>