<div class="tag_create_blog">
	<form class="form form-horizontal create-article-form" method="post" id="insert-blog" action="#">
		<div class="valign tag_cr_blog_hdr">
			<div class="valign wo_page_hdng">
				<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M17,14H19V17H22V19H19V22H17V19H14V17H17V14M20,11V8H4V11H20M13,13V14.68C12.37,15.63 12,16.77 12,18C12,19.09 12.29,20.12 12.8,21H4A2,2 0 0,1 2,19V3L3.67,4.67L5.33,3L7,4.67L8.67,3L10.33,4.67L12,3L13.67,4.67L15.33,3L17,4.67L18.67,3L20.33,4.67L22,3V13.5C20.93,12.58 19.53,12 18,12C16.77,12 15.63,12.37 14.68,13H13M11,19V13H4V19H11Z"></path></svg></span> <?php echo $wo['lang']['create_new_article'];?>
			</div>
			<div>
				<a class="btn btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=my-blogs');?>"><?php echo $wo['lang']['go_back'];?></a>
				<button class="btn btn-main btn-mat disable_btn" type="submit"><?php echo $wo['lang']['publish']; ?></button>
			</div>
		</div>
		<div class="tag_cr_blog_main tag_scroll">
			<div class="container">
				<div class="setting-update-alert" id="blog-alert"></div>
				<div class="tag_cr_blog_fields">
					<textarea name="blog_title" id="blog_title" class="auto-resize blog_title" rows="1" placeholder="<?php echo $wo['lang']['title_more_than10']; ?>"></textarea>
				</div>
				<div class="tag_cr_blog_fields">
					<textarea name="blog_description" id="new-blog-desc" class="auto-resize blog_description" rows="1" placeholder="<?php echo $wo['lang']['desc_more_than32']; ?>"></textarea>
				</div>
				<div name="blog_content" class="tag_cr_blog_write" id="blog_content" data-phold="<?php echo $wo['lang']['write_something_here'] ?>"></div> 
			</div>
		</div>
		<div class="tag_cr_blog_side tag_scroll">
			<div class="tag_alone_label">
				<label><?php echo $wo['lang']['thumbnail'];?></label>
			</div>
			<div class="wow_fcov_image tag_cr_blog_img" data-block="thumdrop-zone" onclick="document.getElementById('thumbnail').click(); return false">
				<div class="valign upload_ad_image">
					<div class="btn btn-mat btn-default upload_ad_image_content">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1,3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z"></path></svg> <?php echo $wo['lang']['browse_to_upload']; ?>
					</div>
					<p class="mb-0"><?php echo $wo['lang']['drop_img_here'] ?></p>
				</div>
				<div id="wow_fcov_img_holder"></div>
			</div>
			<label class="tag_field">
				<select name="blog_category" id="blog_category">
					<option value="0"><?php echo $wo['lang']['category'];?></option>
					<?php foreach ($wo['blog_categories'] as $category_id => $category_name): ?>
						<option value="<?php echo $category_id?>"><?php echo $category_name; ?></option>
					<?php endforeach; ?>
				</select>
				<span><?php echo $wo['lang']['category'] ?></span>
			</label>
			<label class="tag_field">
				<input data-role="tagsinput" id="blog_tags" name="blog_tags" type="text" placeholder=" ">
				<span><?php echo $wo['lang']['tags'] ?></span>
			</label>
		</div>
		<input type="file" class="hidden" id="thumbnail" name="thumbnail" accept="image/*">
		<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
		<input name="image" type="file" id="upload" class="hidden">
	</form>
</div>

<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script>
jQuery(document).ready(function($) {
    var thumb_drop_block = $("[data-block='thumdrop-zone']");
    if (typeof(window.FileReader) == 'undefined') {
      thumb_drop_block.find('.thumbnail-rendderer div').text('Drag drop is not supported in your browser!');
    }
    else{
      thumb_drop_block[0].ondragover = function() {
          thumb_drop_block.addClass('hover');
          return false;
      };
          
      thumb_drop_block[0].ondragleave = function() {
          thumb_drop_block.removeClass('hover');
          return false;
      };

      thumb_drop_block[0].ondrop = function(event) {
          event.preventDefault();
          thumb_drop_block.removeClass('hover');
          var file = event.dataTransfer.files;
          $("#thumbnail").prop('files', file);
          $("#wow_fcov_img_holder").html("<img src='" + window.URL.createObjectURL(event.dataTransfer.files[0]) + "' alt='Picture'>")
      };
    }

    $("#blog_tags").tagsinput({
      maxTags: 15,
    });

    $("#thumbnail").change(function(event) {
      $("#wow_fcov_img_holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
    });


    $('#insert-blog').ajaxForm({
      url: Wo_Ajax_Requests_File() + '?f=insert-blog',
      beforeSend: function() {
        $('#insert-blog').find('.disable_btn').attr('disabled','disabled');
      },
      success: function(data) {
        if (data['status'] == 200) {
          $("#blog-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
          window.location = data.url;
        } else if (data['status'] == 300) {
			$("body").snackbar({
				message: "<?php echo $wo['lang']['approve_post_text']; ?>"
			});
          Wo_Delay(function(){
            location.reload();
          },3000);
        } else if (data['message']) {
          $("#blog-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
        } 
        $('#insert-blog').find('.disable_btn').removeAttr("disabled");
      }});
 });

tinymce.init({
	selector: '#blog_content',
	menubar: false,
	<?php if (Wo_IsMobile() == false) { ?>
	inline: true,
	<?php } ?>
	theme: 'inlite',
	images_upload_credentials: true,
	paste_data_images: true,
	entity_encoding : "raw",
	images_upload_url: Wo_Ajax_Requests_File() + '?f=upload-blog-image',
	toolbar: "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | forecolor backcolor",
	insert_toolbar: 'image hr quicktable pagebreak | numlist bullist | h2 h3 | media link',
	selection_toolbar: 'undo redo | bold italic underline | strikethrough forecolor | h2 h3 | alignleft aligncenter alignright | blockquote quicklink',
	contextmenu: 'inserttable | cell row column deletetable',
	plugins: [
      "advlist autolink lists link image hr anchor pagebreak media",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime nonbreaking save table contextmenu directionality",
      "paste textcolor colorpicker textpattern"
    ],
    file_picker_callback: function(callback, value, meta) {
      if (meta.filetype == 'image') {
        $('#upload').trigger('click');
        $('#upload').on('change', function() {
          var file = this.files[0];
          var reader = new FileReader();
          reader.onload = function(e) {
            callback(e.target.result, {
              alt: ''
            });
          };
          reader.readAsDataURL(file);
        });
      }
    },
	mobile: {
		theme: 'mobile'
	},
});
</script> 