<div class="tag_create_blog">
	<form class="form form-horizontal create-article-form" method="post" id="update-blog" action="#">
		<div class="valign tag_cr_blog_hdr">
			<div class="valign wo_page_hdng">
				<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11H4V8H20M20,15H13V13H20M20,19H13V17H20M11,19H4V13H11M20.33,4.67L18.67,3L17,4.67L15.33,3L13.67,4.67L12,3L10.33,4.67L8.67,3L7,4.67L5.33,3L3.67,4.67L2,3V19A2,2 0 0,0 4,21H20A2,2 0 0,0 22,19V3L20.33,4.67Z"></path></svg></span> <?php echo $wo['lang']['edit'];?>
			</div>
			<div>
				<a class="btn btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=my-blogs');?>"><?php echo $wo['lang']['go_back'];?></a>
				<button class="btn btn-main btn-mat disable_btn" type="submit"><?php echo $wo['lang']['save']; ?></button>
			</div>
		</div>
		<div class="tag_cr_blog_main tag_scroll">
			<div class="container">
				<div class="create-article-alerts" id="blog-alert"></div>
				<div class="tag_cr_blog_fields">
					<textarea name="blog_title" id="blog_title" class="auto-resize blog_title" rows="1" placeholder="<?php echo $wo['lang']['title_more_than10']; ?>"><?php echo $wo['article']['title']?></textarea>
				</div>
				<div class="tag_cr_blog_fields">
					<textarea name="blog_description" id="new-blog-desc" class="auto-resize blog_description" rows="1" placeholder="<?php echo $wo['lang']['desc_more_than32']; ?>"><?php echo $wo['article']['description']?></textarea>
				</div>
				<textarea name="blog_content" class="tag_cr_blog_write mce-content-body" id="blog_content" data-phold="<?php echo $wo['lang']['write_something_here'] ?>"><?php echo $wo['article']['content']?></textarea> 
			</div>
		</div>
		<div class="tag_cr_blog_side tag_scroll">
			<div class="tag_alone_label">
				<label><?php echo $wo['lang']['thumbnail'];?></label>
			</div>
			<div class="wow_fcov_image tag_cr_blog_img pointer" data-block="thumdrop-zone" onclick="document.getElementById('thumbnail').click(); return false">
				<div id="wow_fcov_img_holder"><img src="<?php echo $wo['article']['thumbnail']; ?>" alt=""></div>
			</div>
			<label class="tag_field">
				<select name="blog_category" id="blog_category">
					<option value="0"><?php echo $wo['lang']['category'];?></option>
					<?php foreach ($wo['blog_categories'] as $category_id => $category_name):?>
						<option value="<?php echo $category_id?>" <?php if($category_id == $wo['article']['category']) echo "selected='selected'" ;?> ><?php echo $category_name;?></option>
					<?php endforeach;?>
				</select>
				<span><?php echo $wo['lang']['category'] ?></span>
			</label>
			<label class="tag_field">
				<input data-role="tagsinput" value="<?php echo $wo['article']['tags']?>" id="blog_tags" name="blog_tags" type="text" placeholder=" ">
				<span><?php echo $wo['lang']['tags'] ?></span>
			</label>
		</div>
		<input type="file" class="hidden" id="thumbnail" name="thumbnail" accept="image/*">
		<input name="image" type="file" id="upload" class="hidden" onchange="">
		<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
	</form>
</div>

<script src="<?php echo $wo['config']['theme_url'];?>/javascript/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>

<script>
 jQuery(document).ready(function($) {
    var thumb_drop_block = $("[data-block='thumdrop-zone']");

    if (typeof(window.FileReader) == 'undefined') {
      thumb_drop_block.find('.error-text-renderer').text('Drag drop is not supported in your browsers!');
    }

    else{
      thumb_drop_block[0].ondragover = function() {
          thumb_drop_block.addClass('hover');
          return false;
      };
          
      thumb_drop_block[0].ondragleave = function() {
          thumb_drop_block.removeClass('hover');
          return false;
      };

      thumb_drop_block[0].ondrop = function(event) {
          event.preventDefault();
          thumb_drop_block.removeClass('hover');
          var file = event.dataTransfer.files;
          $("#thumbnail").prop('files', file);
		  $("#wow_fcov_img_holder").html("<img src='" + window.URL.createObjectURL(event.dataTransfer.files[0]) + "' alt='Picture'>")
      };
    }

    $("#thumbnail").change(function(event) {
	  $("#wow_fcov_img_holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
    });

    $("#blog_tags").tagsinput({
      maxTags: 15,
    })


    $('#update-blog').ajaxForm({
      url: Wo_Ajax_Requests_File() + '?f=update-blog&blog_id=<?php echo $wo['article']['id'];?>',
      beforeSend: function() {
        $('#update-blog').find('.disable_btn').attr('disabled','disabled');
      },
      success: function(data) {
        if (data['status'] == 200) {
          $("#blog-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
          window.location = data.url;
        } else if (data['message']) {
          $("#blog-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
        } 
        $('#update-blog').find('.disable_btn').removeAttr("disabled");
      }
    });

 });

tinymce.init({
	selector: '#blog_content',
	menubar: false,
	images_upload_credentials: true,
	paste_data_images: true,
	entity_encoding : "raw",
	images_upload_url: Wo_Ajax_Requests_File() + '?f=upload-blog-image',
	toolbar: "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link media image | forecolor backcolor",
	contextmenu: 'inserttable | cell row column deletetable',
	plugins: [
      "advlist autolink lists link image hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "paste textcolor colorpicker textpattern"
    ],
    file_picker_callback: function(callback, value, meta) {
      if (meta.filetype == 'image') {
        $('#upload').trigger('click');
        $('#upload').on('change', function() {
          var file = this.files[0];
          var reader = new FileReader();
          reader.onload = function(e) {
            callback(e.target.result, {
              alt: ''
            });
          };
          reader.readAsDataURL(file);
        });
      }
    },
});
</script> 