<?php if ($wo['page_data']['page_type'] == 0) { ?>
	<div class="page-margin">
		<div class="container">
			<div class="wow_content p20">
				<?php echo htmlspecialchars_decode($wo['page_data']['page_content']);?>
			</div>
		</div>
	</div>
<?php } else { ?>
	<div class="page-margin">
		<div class="container">
			<h2 class="tag_page_title m5"><?php echo $wo['page_data']['page_title']?></h2>
			<div class="page-margin">
				<div class="wow_content p20">
					<?php echo htmlspecialchars_decode($wo['page_data']['page_content']);?>
				</div>
			</div>
		</div>
	</div>
<?php } ?>