<div class="valign tag_404 tag_maint_page">
	<div class="text-center tag_404_innr">
		<img src="<?php echo $wo['config']['theme_url'];?>/img/maintenance.svg" />
		<h2>We’ll be back soon!</h2>
		<p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment. If you need help you can always <a class="main" href="mailto:<?php echo $wo['config']['siteEmail']; ?>">contact us</a>, otherwise we&rsquo;ll be back online shortly!</p>
		<p>&mdash; <?php echo $wo['config']['siteName'];?></p>
	</div>
</div>