<div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 user-data" data-page-id="<?php echo $wo['GroupList']['id'];?>">
	<div class="wow_content wow_my_groups">
		<div class="avatar">
			<a href="<?php echo $wo['GroupList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['GroupList']['username'];?>">
				<img src="<?php echo $wo['GroupList']['cover'];?>" alt="<?php echo $wo['GroupList']['name']; ?>" />
			</a>
		</div>
		<div class="wow_my_groups_info">
			<h3 class="truncate page_title"><a href="<?php echo $wo['GroupList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['GroupList']['username'];?>"><?php echo $wo['GroupList']['group_title']; ?></a></h3>
			<p><?php echo Wo_CountGroupMembers($wo['GroupList']['id']);?> <?php echo $wo['lang']['members']; ?></p>
			<?php echo Wo_GetJoinButton($wo['GroupList']['id']);?>
		</div>
	</div>
</div>