<div class="valign author-block tag_boost_page user-data" data-page-id="<?php echo $wo['PageList']['page_id'];?>">
	<div class="valign author">
		<div class="img-wrap">
			<a href="<?php echo $wo['PageList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['PageList']['username'];?>"><img src="<?php echo $wo['PageList']['avatar'];?>" alt="<?php echo $wo['PageList']['name']; ?>" /></a>
		</div>
		<div class="text">
			<h3><a href="<?php echo $wo['PageList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['PageList']['username'];?>"><?php echo $wo['PageList']['name']; ?></a></h3>
			<p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg> <?php echo Wo_CountPageLikes($wo['PageList']['page_id']);?> <?php echo $wo['lang']['people_likes_this']; ?></p>
			<p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M5.5,7A1.5,1.5 0 0,1 4,5.5A1.5,1.5 0 0,1 5.5,4A1.5,1.5 0 0,1 7,5.5A1.5,1.5 0 0,1 5.5,7M21.41,11.58L12.41,2.58C12.05,2.22 11.55,2 11,2H4C2.89,2 2,2.89 2,4V11C2,11.55 2.22,12.05 2.59,12.41L11.58,21.41C11.95,21.77 12.45,22 13,22C13.55,22 14.05,21.77 14.41,21.41L21.41,14.41C21.78,14.05 22,13.55 22,13C22,12.44 21.77,11.94 21.41,11.58Z" /></svg> <?php echo $wo['PageList']['category']; ?></p>
		</div>            
	</div>
	<div>
		<?php echo Wo_GetLikeButton($wo['PageList']['page_id']);?>
	</div>              
</div>