<div class="valign tag_404 wow_upgrd_ico"> 
	<?php $user_pro_type = Wo_GetUserProType();	?>
	<div class="text-center tag_404_innr">
   	    <?php 
        $string = str_replace('{color}', $user_pro_type['color_name'], $wo['lang']['cong']);
        $string = str_replace('{icon}', $user_pro_type['icon'], $string);
        $string = str_replace('{type_name}', $user_pro_type['type_name'], $string);
        ?>
		<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 367.805 367.805" xml:space="preserve"> <g> <path style="fill:#3BB54A;" d="M183.903,0.001c101.566,0,183.902,82.336,183.902,183.902s-82.336,183.902-183.902,183.902 S0.001,285.469,0.001,183.903l0,0C-0.288,82.625,81.579,0.29,182.856,0.001C183.205,0,183.554,0,183.903,0.001z"/> <polygon style="fill:#fff;" points="285.78,133.225 155.168,263.837 82.025,191.217 111.805,161.96 155.168,204.801 256.001,103.968"/> </g></svg>
		<h2><?php echo $wo['lang']['pro_con']; ?> <?php echo $user_pro_type['type_name']; ?></h2>
		<div><a href="<?php echo Wo_SeoLink('index.php?link1=welcome');?>" class="btn btn-mat btn-main"><?php echo $wo['lang']['cong_2']; ?></a></div>
	</div>
</div>