<div class="valign thread-replies" data-thread-reply="<?php echo $wo['threadreply']['id']; ?>" id="reply-<?php echo $wo['threadreply']['id']; ?>">
	<div class="avatar">
		<a href="<?php echo ($wo['threadreply']['user_data']['url']); ?>" data-ajax="?link1=timeline&u=<?php echo $wo['threadreply']['user_data']['username']; ?>"><img src="<?php echo $wo['threadreply']['user_data']['avatar']; ?>" alt="Avatar"></a>
	</div>
	<div class="t-right_prt">
		<h4 class="user-title-thread">
			<a href="<?php echo ($wo['threadreply']['user_data']['url']); ?>" data-ajax="?link1=timeline&u=<?php echo $wo['threadreply']['user_data']['username']; ?>"><?php echo ($wo['threadreply']['user_data']['name']); ?></a><span class="middot">·</span><span class="time"><time><?php echo Wo_Time_Elapsed_String($wo['threadreply']['posted_time']); ?></time></span>
		</h4>
		<div class="clear"></div>
		<div class="desc"><?php echo Wo_BbcodeToHtml($wo['threadreply']['post_text']); ?></div>
		<div class="sun_forum_opts">
			<a class="btn btn-main-rev btn-mat" href="<?php echo $wo['threadreply']['reply-url']; ?>" data-ajax="?link1=threadquote&tid=<?php echo $wo['threadreply']['id'];?>"><svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 24 24"><path fill="currentColor" d="M10,9V5L3,12L10,19V14.9C15,14.9 18.5,16.5 21,20C20,15 17,10 10,9Z" /></svg> <?php echo $wo['lang']['reply']; ?></a>
		    <?php if ($wo['threadreply']['is_owner'] || $wo['threadreply']['is_admin']): ?>
			    <a class="btn btn-default btn-mat" href="<?php echo $wo['threadreply']['edit-url']; ?>" data-ajax="?link1=editreply&tid=<?php echo $wo['threadreply']['id'];?>"><svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 24 24"><path fill="currentColor" d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z" /></svg> <?php echo $wo['lang']['edit']; ?></a>
				<a class="btn btn-default delete-reply btn-mat" id="<?php echo $wo['threadreply']['id']; ?>"><svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 24 24"><path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" /></svg> <?php echo $wo['lang']['delete']; ?></a>
		    <?php endif; ?>
		</div>
	</div>
</div>