<div class="movies-comment-item" data-movies-comment="<?php echo $wo['comment']['id']; ?>">
	<div>
		<div class="<?php echo Wo_RightToLeft('pull-left');?> movies-comment-item-img">
			<img src="<?php echo $wo['comment']['user_data']['avatar']; ?>" alt="" class="rounded-circle">
		</div>
		<div class="movies-comment-item-body">
			<h5>
				<a class="pointer bold" data-ajax="?link1=timeline&u=<?php echo $wo['comment']['user_data']['username']; ?>" href="<?php echo $wo['comment']['user_data']['url']; ?>">
					<?php echo $wo['comment']['user_data']['name']; ?>
				</a>
				<span class="time">
					<span class="ajax-time" title="<?php echo date('c',$wo['comment']['posted']); ?>">
						<?php echo Wo_Time_Elapsed_String($wo['comment']['posted']); ?>
					</span>
				</span>
				<?php if ($wo['comment']['is_owner']): ?>
					<span class="pointer <?php echo Wo_RightToLeft('pull-right');?> del-movies-comment" id="<?php echo $wo['comment']['id']; ?>">
						<svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24"><path opacity=".8" fill="#fff" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" /></svg>
					</span>
				<?php endif ?>
			</h5>
			<p><?php echo $wo['comment']['text']; ?></p>
			<div>
				<span class="comment-icons">
					<span class="pointer reply-tomovie-comm" id="<?php echo $wo['comment']['id']; ?>"><svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24"><path fill="currentColor" d="M10,9V5L3,12L10,19V14.9C15,14.9 18.5,16.5 21,20C20,15 17,10 10,9Z" /></svg></span>
					&nbsp;
					<span class="pointer add-movies-commlikes-<?php echo $wo['comment']['id']; ?>" onclick="Wo_AddMovieCommentLike(<?php echo $wo['comment']['id']; ?>)">
						<svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24"><path fill="currentColor" d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" /></svg>
					</span> 
					<span id="movies-comment-likes" data-movies-comlikes="<?php echo $wo['comment']['id']; ?>">
						<?php if ($wo['comment']['likes'] > 0): ?>
							<?php echo $wo['comment']['likes']; ?>
						<?php endif; ?>
					</span>
					&nbsp;
					<span class="pointer add-movies-commlikes-<?php echo $wo['comment']['id']; ?>" onclick="Wo_AddMovieCommentDisLike(<?php echo $wo['comment']['id']; ?>)">
						<svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24"><path fill="currentColor" d="M19,15H23V3H19M15,3H6C5.17,3 4.46,3.5 4.16,4.22L1.14,11.27C1.05,11.5 1,11.74 1,12V14A2,2 0 0,0 3,16H9.31L8.36,20.57C8.34,20.67 8.33,20.77 8.33,20.88C8.33,21.3 8.5,21.67 8.77,21.94L9.83,23L16.41,16.41C16.78,16.05 17,15.55 17,15V5C17,3.89 16.1,3 15,3Z" /></svg>
					</span>
					<span id="movies-comment-likes" data-movies-comdislikes="<?php echo $wo['comment']['id']; ?>">
						<?php if ($wo['comment']['dislikes'] > 0): ?>
							<?php echo $wo['comment']['dislikes']; ?>
						<?php endif; ?>
					</span>
				</span>
				&nbsp;
				<?php if (count($wo['comment']['replies']) > 5): ?>
					<span class="pointer"><?php echo $wo['lang']['replies']; ?></span>
				<?php endif; ?>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="movies-comment-reply-cont">
		<?php 
			foreach ($wo['comment']['replies'] as $wo['comm-reply']) {
				echo Wo_LoadPage('movies/includes/commreplies-list');
			}
		?>
	</div>
	<?php if ($wo['loggedin'] == true) { ?>
		<div class="movies-comment-reply-box hidden">
			<form class="form">
				<div class="form-group">
					<textarea class="form-control movies-comment-reply" onkeydown="Wo_RegisterMovieCommReply(<?php echo $wo['comment']['id']; ?>,event,this)" placeholder="<?php echo $wo['lang']['write_comment'];?>" type="text"></textarea>
				</div>
			</form>
		</div>
	<?php } ?>
</div>