<div class="col-xl-3 col-lg-4 col-md-4 col-sm-4 col-6 movies-film-wrapper-lmore" data-film-id="<?php echo $wo['film']['id']; ?>">
	<div class="text-center movies-film-wrapper">
		<a href="<?php echo $wo['film']['url']; ?>">
			<div class="avatar">
				<img src="<?php echo $wo['film']['cover']; ?>" alt="<?php echo $wo['film']['name']; ?>">
			</div>
			<h3 class="truncate bold" title="<?php echo $wo['film']['name']; ?>"><?php echo $wo['film']['name']; ?></h3>
			<p class="truncate"><?php echo $wo['film']['genre']; ?></p>
		</a>
	</div>
</div>