<div class="col-xl-3 col-lg-4 col-md-4 col-sm-4 col-6">
	<div class="text-center movies-film-wrapper">
		<a href="<?php echo $wo['filmInfo']['url']; ?>">
			<div class="avatar">
				<img src="<?php echo $wo['filmInfo']['cover']; ?>" alt="<?php echo $wo['filmInfo']['name']; ?>">
			</div>
			<h3 class="truncate bold" title="<?php echo $wo['filmInfo']['name']; ?>"><?php echo $wo['filmInfo']['name']; ?></h3>
			<p class="truncate"><?php echo $wo['filmInfo']['release']; ?></p>
		</a>
	</div>
</div>