<div class="wow_sett_content">
	<form method="post" class="form-horizontal setting-information-form">
		<div class="setting-information-alert setting-update-alert"></div>
		<label class="tag_field">
			<select id="privacy" name="privacy">
				<?php 
					$selected_privacy_yes   = ($wo['setting']['privacy'] == 1)   ? ' selected' : '';
					$selected_privacy_no  = ($wo['setting']['privacy'] == 2)   ? ' selected' : '';
				?>
				<option value="1" <?php echo $selected_privacy_yes; ?>><?php echo $wo['lang']['public'];?> </option>
				<option value="2" <?php echo $selected_privacy_no; ?>><?php echo $wo['lang']['private'];?> </option>
			</select>
			<span><?php echo $wo['lang']['group_type']; ?></span>
		</label>
		<label class="tag_field">
			<select id="join_privacy" name="join_privacy">
				<?php 
					$selected_followp_yes   = ($wo['setting']['join_privacy'] == 1)   ? ' selected' : '';
					$selected_followp_no  = ($wo['setting']['join_privacy'] == 2)   ? ' selected' : '';
				?>
				<option value="1" <?php echo $selected_followp_yes; ?>><?php echo $wo['lang']['no'];?></option>
				<option value="2" <?php echo $selected_followp_no; ?>><?php echo $wo['lang']['yes'];?></option>
			</select>
			<span><?php echo $wo['lang']['confirm']; ?></span>
		</label>
		<div class="help-block"><?php echo $wo['lang']['confirm_request_group_privacy_label'];?></div>
		<div class="text-center">
            <button class="btn btn-main btn-mat btn-mat-raised disable_btn" type="submit"><?php echo $wo['lang']['save']; ?></button>
		</div>
		<input type="hidden" name="group_id" value="<?php echo $wo['setting']['id'];?>">
		<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
	</form>
</div>

<script type="text/javascript">
$(function() {
  $('form.setting-information-form').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=groups&s=update_privacy_setting',
    beforeSend: function() {
      $('.setting-information-form').find('.disable_btn').attr('disabled','disabled');
    },
    success: function(data) {
      if (data.status == 200) {
        scrollToTop();
        $('.setting-information-alert').html('<div class="alert alert-success">' + data.message + '</div>');
        $('.alert-success').fadeIn('fast', function() {
          $(this).delay(2500).slideUp(500, function() {
            $(this).remove();
          });
        });
      }
      $('.setting-information-form').find('.disable_btn').removeAttr("disabled");
    }
  });
});
</script>