<div class="col-6 col-md-4 col-lg-3 nearby_user_wrapper user-data" id="request-<?php echo $wo['request']['user_id'] ?>">
	<div class="nearby_user_wrapper_innr text-center">
		<div class="avatar">
			<a href="<?php echo $wo['request']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['request']['username'];?>"><img src="<?php echo $wo['request']['avatar'];?>" alt="<?php echo $wo['request']['name']; ?>" /></a>
		</div>
		<a href="<?php echo $wo['request']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['request']['username'];?>" class="truncate user_wrapper_link"><?php echo $wo['request']['name']; ?></a>
		<div class="user-follow-button">
			<span onclick="Wo_AcceptJoinGroup(<?php echo $wo['request']['user_id']?>, <?php echo $wo['setting']['id']?>);" class="btn btn-success btn-sm"><?php echo $wo['lang']['accept']; ?></span>
			<span onclick="Wo_DeleteJoinGroup(<?php echo $wo['request']['user_id']?>, <?php echo $wo['setting']['id']?>);" class="btn btn-danger btn-sm"><?php echo $wo['lang']['delete']; ?></span>
		</div>
	</div>
</div>