<?php
$messages = Wo_GetGroupMessagesAPP(array('group_id' => $wo['group']['group_id'],'limit' => 1));
$message = array();
if (!empty($messages) && !empty($messages[0])) {
   $message = $messages[0];
   
   if (strlen($message['orginal_text']) > 100) {
      $message['orginal_text'] = mb_substr( $message['orginal_text'], 0, 97, "utf-8") . '...';
   }
}
$unread_class = '';
if (!empty($message) && isset($message['time']) && isset($message['from_id']) && $message['from_id'] != $wo['user']['id']) {
   if ($message['time'] > $wo['user']['lastseen']) {
       $unread_class = ' unread';
   }
}

$message_event = "Wo_OpenChatTab(0,".$wo['group']['group_id'].");";
$message['orginal_text'] = Wo_Emo($message['orginal_text']);
?>
<div class="notification-list pointer messages-list <?php echo $unread_class;?>" onclick="<?php echo $message_event ?>">
	<div class="valign">
		<div class="notification-user-avatar">
			<img src="<?php echo $wo['group']['avatar'];?>" alt="<?php echo $wo['group']['group_name']; ?>">
		</div>
		<div class="notification-text">
			<div class="ajax-time" title="<?php echo (!empty($message['time'])) ? date('c',$message['time']) : '';?>"><?php echo (!empty($message['time'])) ? Wo_Time_Elapsed_String($message['time']) : '';?></div>
            <span><?php echo $wo['group']['group_name']; ?></span>
            <?php if (!empty($message['from_id'])): ?>
				<div class="header-message">
					<?php echo ($wo['user']['id'] == $message['from_id']) ? $wo['lang']['me'] . ': ' : '';?>
					<?php echo (!empty($message['media'])) ? '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"><path fill="#000000" d="M7.5,18A5.5,5.5 0 0,1 2,12.5A5.5,5.5 0 0,1 7.5,7H18A4,4 0 0,1 22,11A4,4 0 0,1 18,15H9.5A2.5,2.5 0 0,1 7,12.5A2.5,2.5 0 0,1 9.5,10H17V11.5H9.5A1,1 0 0,0 8.5,12.5A1,1 0 0,0 9.5,13.5H18A2.5,2.5 0 0,0 20.5,11A2.5,2.5 0 0,0 18,8.5H7.5A4,4 0 0,0 3.5,12.5A4,4 0 0,0 7.5,16.5H17V18H7.5Z" /></svg> ' . $wo['lang']['file_n_label'] : $message['orginal_text']; ?>
				</div>
            <?php endif ?>
		</div>
	</div>
</div>