<?php 
$wondertage_settings = array();
if (mysqli_query($wo['sqlConnect'], "DESCRIBE `wondertage_settings`" )) {
	$settings = $db->get('wondertage_settings');
	foreach ($settings as $key => $value) {
		$wondertage_settings[$value->name] = $value->value;
	}
}
?>
<?php if(Wo_IsAdmin()) { ?>
	<div class="modal fade" id="tag_settings" role="dialog" aria-hidden="false">
		<style>
		.modal-dialog .tag_theme_opts_close {opacity: 1;padding: 4px;margin: 0;box-shadow: 0 3px 1px -2px rgba(0,0,0,.2), 0 2px 2px 0 rgba(0,0,0,.14), 0 1px 5px 0 rgba(0,0,0,.12);border-radius: 50%;font-size: inherit;}
		.modal-dialog .tag_theme_opts_close svg {width: 22px;height: 22px;}
		.tag_theme_opts_hdr {margin-bottom: 20px;}
		.tag_theme_opts_hdr img {width: 65px;height: 65px;margin-right: 15px;}
		.bmc-btn {color: #000;background: linear-gradient(to right, #ffe958, #ffcd00);min-width: 160px;}
		.bmc-btn svg {height: 22px;width: 22px;}
		.tag_theme_opts_p {font-weight: 500;letter-spacing: 1px;font-size: 13px;text-transform: uppercase;margin: 20px 0 10px;}
		.wondertag_form .modal-body {max-height: calc(100vh - 100px);overflow: hidden;margin: -10px -24px -24px;padding: 0 24px 10px;}
		.themedonate_done .wondertag_form .modal-body {overflow-y: auto;}
		.wondertag_form .tag_onboarding {top: 0;right: 0;bottom: 0;left: 0;border-radius: 0 0 10px 10px;backdrop-filter: blur(5px);background-color: rgb(255 255 255 / 85%);}
		<?php if ($_COOKIE['mode'] == 'night') { ?>
		.wondertag_form .tag_onboarding {background-color: rgb(33 33 33 / 85%);}
		<?php } ?>
		.wondertag_form .tag_onboarding img {max-width: 100px;}
		.wondertag_form .tag_onboarding > p {letter-spacing: normal;}
		.tag_theme_opts_space {background: rgb(0 0 0 / 0.1);height: 10px;margin: 15px -24px 0;}
		.tag_theme_opts_check input, .themedonate_done .theme_opt_onboard {display: none;}
		.tag_theme_opts_check label {justify-content: space-between;margin: 0;width: 100%;}
		.tag_theme_opts_check span {display: inline-block;width: 51px;min-width: 51px;height: 30px;background-color: #e9e9e9;border-radius: 15px;position: relative;transition: .3s all ease-in-out;cursor: pointer;margin: 0 0 0 10px;}
		.tag_theme_opts_check span::after {content: '';display: inline-block;width: 26px;height: 26px;background-color: #fff;border-radius: 14px;position: absolute;top: 2px;transform: translateX(2px);box-shadow: 0 0 4px rgb(0 0 0 / 0.15);transition: .3s all ease-in-out;}
		.tag_theme_opts_check input:checked + label span {background-color: #30d158;}
		.tag_theme_opts_check input:checked + label span::after {transform: translateX(23px);box-shadow: -10px 0 40px rgba(0, 0, 0, .10);}
		</style>
		<div class="modal-dialog modal-md wow_mat_mdl">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">Theme Options</h4>
					<button type="button" class="close tag_theme_opts_close" data-dismiss="modal" aria-label="Close"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M18.3 5.71c-.39-.39-1.02-.39-1.41 0L12 10.59 7.11 5.7c-.39-.39-1.02-.39-1.41 0-.39.39-.39 1.02 0 1.41L10.59 12 5.7 16.89c-.39.39-.39 1.02 0 1.41.39.39 1.02.39 1.41 0L12 13.41l4.89 4.89c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L13.41 12l4.89-4.89c.38-.38.38-1.02 0-1.4z"></path></svg></button>
				</div>
				<div class="wondertag_alert"></div>
				<?php if (!mysqli_query($wo['sqlConnect'], "DESCRIBE `wondertage_settings`" )) { ?>
					<div class="alert alert-info">Make sure you are using the latest version of the Script or v3.2 to use the Theme Options</div>
					<div class="alert alert-info">If you are using the latest version of the Script, but still not able to access the Theme Options, create a support ticket <a href="https://bit.ly/k97Support">here</a></div>
				<?php } ?>
				<form class="wondertag_form" method="POST">
					<div class="modal-body tag_scroll">
						<div class="valign tag_onboarding theme_opt_onboard">
							<img src="https://k97.in/theme/wondertag/hug.gif">
							<h2>Donate Us. Show some Love.</h2>
							<p>If you can, please donate to us. Your donation will mean a lot.<br>Donations will help to maintain the Wondertag theme project and our expenses.<br>So, we can provide the theme and services at low prices.</p>
							<span class="valign">
								<a class="btn btn-mat btn-main tag_onboard_donate_btn" target="_blank" href="http://bit.ly/BuyThemelatedCoffee">Donate Now</a>
								&nbsp;&nbsp;<button type="button" class="btn btn-mat btn-default tag_onboard_donate_btn">I don't want to</button>
							</span>
						</div>
						<div class="valign tag_theme_opts_hdr">
							<img src="<?php echo $wo['config']['theme_url'];?>/themeLogo.png" alt="<?php echo $wo['config']['siteName'];?>"/>
							<div class="full_width">
								<h6>Wondertag <span class="badge badge-secondary bold">v2.3.6</span></h6>
								<div>
									<a class="btn btn-mat bmc-btn" target="_blank" href="http://bit.ly/BuyThemelatedCoffee"><svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24" viewBox="0 0 24 24" width="24"><g><rect fill="none" height="24" width="24"/></g><g fill="currentColor"><g><path d="M3,11L3,11c-1.1,0-2,0.9-2,2v7c0,1.1,0.9,2,2,2h0c1.1,0,2-0.9,2-2v-7C5,11.9,4.1,11,3,11z"/><path d="M10,5.3C10,3.45,11.45,2,13.3,2c1.04,0,2.05,0.49,2.7,1.25C16.65,2.49,17.66,2,18.7,2C20.55,2,22,3.45,22,5.3 c0,2.1-2.5,4.51-5.33,7.09c-0.38,0.35-0.97,0.35-1.35,0C12.5,9.81,10,7.4,10,5.3"/><path d="M19.99,17h-6.83c-0.11,0-0.22-0.02-0.33-0.06l-1.47-0.51c-0.26-0.09-0.39-0.37-0.3-0.63l0,0c0.09-0.26,0.38-0.4,0.64-0.3 l1.12,0.43c0.11,0.04,0.24,0.07,0.36,0.07h2.63c0.65,0,1.18-0.53,1.18-1.18v0c0-0.49-0.31-0.93-0.77-1.11L9.3,11.13 C9.08,11.04,8.84,11,8.6,11H7v9.02l6.37,1.81c0.41,0.12,0.85,0.1,1.25-0.05L22,19l0,0C22,17.89,21.1,17,19.99,17z"/></g></g></svg> Donate Us</a>
									<!--<a class="btn btn-mat btn-main-rev" target="_blank" href="https://k97.in/theme/wondertag/">Check for update</a>-->
								</div>
							</div>
						</div>
						<div class="tag_theme_opts_space"></div>
						<p class="tag_theme_opts_p">Header</p>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_header_layout'>
							<input type="checkbox" name="tag_header_layout" id="tag_header_layout" value="1" <?php echo ($wondertage_settings['tag_header_layout'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_header_layout">New Header Layout<span></span></label>
						</div>
						<hr>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_expand_search'>
							<input type="checkbox" name="tag_expand_search" id="tag_expand_search" value="1" <?php echo ($wondertage_settings['tag_expand_search'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_expand_search">Click to Expand Search in Header on Mobile<span></span></label>
						</div>
						<hr>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_anron_ico_head'>
							<input type="checkbox" name="tag_anron_ico_head" id="tag_anron_ico_head" value="1" <?php echo ($wondertage_settings['tag_anron_ico_head'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_anron_ico_head">Enable Anron Premium Icons for Header<span></span></label>
						</div>
						<div class="tag_theme_opts_space"></div>
						<p class="tag_theme_opts_p">Market</p>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_prods_slider'>
							<input type="checkbox" name="tag_prods_slider" id="tag_prods_slider" value="1" <?php echo ($wondertage_settings['tag_prods_slider'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_prods_slider">Enable Random Products Slider<span></span></label>
						</div>
						<hr>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_prods_cat_slider'>
							<input type="checkbox" name="tag_prods_cat_slider" id="tag_prods_cat_slider" value="1" <?php echo ($wondertage_settings['tag_prods_cat_slider'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_prods_cat_slider">Enable Categories Slider<span></span></label>
						</div>
						<hr>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_prods_autoload'>
							<input type="checkbox" name="tag_prods_autoload" id="tag_prods_autoload" value="1" <?php echo ($wondertage_settings['tag_prods_autoload'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_prods_autoload">Enable Auto Load (Infinte scroll) Products<span></span></label>
						</div>
						<div class="tag_theme_opts_space"></div>
						<p class="tag_theme_opts_p">Posts</p>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_artplayer'>
							<input type="checkbox" name="tag_artplayer" id="tag_artplayer" value="1" <?php echo ($wondertage_settings['tag_artplayer'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_artplayer">Use Artplayer as the Video Player<span></span></label>
						</div>
						<hr>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_send_comment'>
							<input type="checkbox" name="tag_send_comment" id="tag_send_comment" value="1" <?php echo ($wondertage_settings['tag_send_comment'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_send_comment">Enable "Click to Send Comment" button<span></span></label>
						</div>
						<hr>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_show_comments'>
							<input type="checkbox" name="tag_show_comments" id="tag_show_comments" value="1" <?php echo ($wondertage_settings['tag_show_comments'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_show_comments">Show Comments in News Feed only if Post has comments<span></span></label>
						</div>
						<div class="tag_theme_opts_space"></div>
						<p class="tag_theme_opts_p">Profile</p>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_profile_qr'>
							<input type="checkbox" name="tag_profile_qr" id="tag_profile_qr" value="1" <?php echo ($wondertage_settings['tag_profile_qr'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_profile_qr">Show Insights and QR in the User profile page<span></span></label>
						</div>
						<div class="tag_theme_opts_space"></div>
						<p class="tag_theme_opts_p">Welcome</p>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_welcome_layout'>
							<input type="checkbox" name="tag_welcome_layout" id="tag_welcome_layout" value="1" <?php echo ($wondertage_settings['tag_welcome_layout'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_welcome_layout">New Welcome Page<span></span></label>
						</div>
						<hr>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_trend'>
							<input type="checkbox" name="tag_trend" id="tag_trend" value="1" <?php echo ($wondertage_settings['tag_trend'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_trend">Show Trending Hashtags on Welcome page<span></span></label>
						</div>
						<div class="tag_theme_opts_space"></div>
						<p class="tag_theme_opts_p">Miscellaneous</p>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_hide_menu'>
							<input type="checkbox" name="tag_hide_menu" id="tag_hide_menu" value="1" <?php echo ($wondertage_settings['tag_hide_menu'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_hide_menu">Hide Menu Links in Left Sidebar for Guest User<span></span></label>
						</div>
						<hr>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_show_side_trend'>
							<input type="checkbox" name="tag_show_side_trend" id="tag_show_side_trend" value="1" <?php echo ($wondertage_settings['tag_show_side_trend'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_show_side_trend">Show Trending Hashtags in Sidebar<span></span></label>
						</div>
						<hr>
						<div class="tag_theme_opts_check">
							<input type='hidden' value='0' name='tag_auto_dark'>
							<input type="checkbox" name="tag_auto_dark" id="tag_auto_dark" value="1" <?php echo ($wondertage_settings['tag_auto_dark'] == 1 ? 'checked' : '') ?>>
							<label class="valign" for="tag_auto_dark">Enable Auto Dark mode based on Device Settings<span></span></label>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<script>
		var donate = window.localStorage.tagOnDonatethree;
		$('body').addClass(donate);
		
		$('.tag_onboard_donate_btn').click(function() {
			if ($("body").hasClass("themedonate_done")) {
				$('body').toggleClass('themedonate_done');
				localStorage.removeItem('tagOnDonatethree');
				localStorage.tagOnDonatethree = "onboard";
			} else {
				$('body').toggleClass('themedonate_done');
				localStorage.removeItem('tagOnDonatethree');
				localStorage.tagOnDonatethree = "themedonate_done";
			}
		});
		<?php if (!mysqli_query($wo['sqlConnect'], "DESCRIBE `wondertage_settings`" )) { ?>
		<?php } else { ?>
			$(function() {
				$('.tag_theme_opts_check input[type="checkbox"]').change(function(){
					$('form.wondertag_form').submit();
				});
				$('form.wondertag_form').ajaxForm({
					url: Wo_Ajax_Requests_File() + '?f=wondertag_theme_settings&s=update',
					beforeSend: function() {
						
					},
					success: function(data) {
						if (data.status == 200) {
							$("body").snackbar({
								message: data.message
							});
						} else {
							$('.wondertag_alert').html('<div class="alert alert-danger">' + data.error + '</div>');
						}
					}
				});
			});
		<?php } ?>
	</script>
<?php } ?>