<div class="live_comments" live_comment_id="<?php echo $wo['comment']['id']; ?>">
	<a onclick="InjectAPI('{&quot;profile_id&quot; : &quot;1&quot;, &quot;type&quot;:&quot;user&quot;}', event);" class="<?php echo Wo_RightToLeft('pull-left'); ?>" href="<?php echo($wo['comment']['publisher']['url']) ?>">
		<img class="avatar" src="<?php echo($wo['comment']['publisher']['avatar']) ?>" alt="avatar">
	</a>
	<div class="comment-body">
		<div class="comment-heading">
			<div class="tag_comm_body">
				<div>
					<span>
						<a href="<?php echo($wo['comment']['publisher']['url']) ?>" data-ajax="?link1=timeline&amp;u=<?php echo($wo['comment']['publisher']['username']) ?>" onclick="InjectAPI('{&quot;profile_id&quot; : &quot;1&quot;, &quot;type&quot;:&quot;user&quot;}', event);">
							<h4 class="user"><?php echo($wo['comment']['publisher']['name']) ?></h4>
						</a>
					</span>
					<?php  if($wo['comment']['publisher']['verified'] == 1) { ?>
					<span class="verified-color" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 512 512"><path d="m256 0c-141.164062 0-256 114.835938-256 256s114.835938 256 256 256 256-114.835938 256-256-114.835938-256-256-256zm0 0" fill="#2196f3"></path><path d="m385.75 201.75-138.667969 138.664062c-4.160156 4.160157-9.621093 6.253907-15.082031 6.253907s-10.921875-2.09375-15.082031-6.253907l-69.332031-69.332031c-8.34375-8.339843-8.34375-21.824219 0-30.164062 8.339843-8.34375 21.820312-8.34375 30.164062 0l54.25 54.25 123.585938-123.582031c8.339843-8.34375 21.820312-8.34375 30.164062 0 8.339844 8.339843 8.339844 21.820312 0 30.164062zm0 0" fill="#fff"></path></svg></span>
					<?php } ?>
				</div>
				<div class="valign">
					<div class="comment-text"><?php echo $wo['comment']['text']; ?></div>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>