<div class="page-margin">
	<div class="container">
		<h2 class="tag_page_title m5"><?php echo $wo['lang']['events']; ?></h2>
		<ul class="list-unstyled tag_page_nav">
			<li class="separate <?php echo ($wo['active'] == "7" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=my-events'); ?>" data-ajax="?link1=my-events"><?php echo $wo['lang']['my_events']; ?></a></li>
			<li class="<?php echo ($wo['active'] == "1" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=events'); ?>" data-ajax="?link1=events"><?php echo $wo['lang']['browse_events'] ?></a></li>
			<li class="<?php echo ($wo['active'] == "2" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=events-going'); ?>" data-ajax="?link1=events-going"><?php echo $wo['lang']['event_going']; ?>	</a></li>
			<li class="<?php echo ($wo['active'] == "3" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=events-invited'); ?>" data-ajax="?link1=events-invited"><?php echo $wo['lang']['event_invited']; ?></a></li>
			<li class="<?php echo ($wo['active'] == "4" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=events-interested'); ?>" data-ajax="?link1=events-interested"><?php echo $wo['lang']['event_intersted']; ?></a></li>
			<li class="<?php echo ($wo['active'] == "5" ? "active" : "")?>"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=events-past'); ?>" data-ajax="?link1=events-past"><?php echo $wo['lang']['events_past']; ?></a></li>
		</ul>
		<div class="page-margin wow_content wow_sett_content">
			<div class="valign wo_page_hdng">
				<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M19,3H18V1H16V3H8V1H6V3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H10V19H5V8H19V9H21V5A2,2 0 0,0 19,3M21.7,13.35L20.7,14.35L18.65,12.35L19.65,11.35C19.85,11.14 20.19,11.13 20.42,11.35L21.7,12.63C21.89,12.83 21.89,13.15 21.7,13.35M12,18.94L18.07,12.88L20.12,14.88L14.06,21H12V18.94Z"></path></svg></span> <?php echo $wo['lang']['edit_event'];?>
			</div>
			<form class="form form-horizontal" method="post" id="update-event">
				<div class="row">
					<div class="col-xl-5">
						<div class="tag_alone_label">
							<label><?php echo $wo['lang']['select_image']; ?></label>
						</div>
						<div class="wow_fcov_image crt_eve_image">
							<div id="wow_fcov_img_holder"><img src="<?php echo $wo['event']['cover']; ?>" alt="<?php echo $wo['event']['name']; ?>"></div>
							<div class="valign upload_ad_image" onclick="document.getElementById('event-cover').click(); return false">
								<div class="btn btn-mat btn-default upload_ad_image_content">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1,3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z"></path></svg> <?php echo $wo['lang']['choose_image'] ?>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xl-7">
						<label class="tag_field">
							<input id="event-name" name="event-name" type="text" placeholder=" " value="<?php echo $wo['event']['name']; ?>">
							<span><?php echo $wo['lang']['event']; ?> <?php echo $wo['lang']['name']; ?></span>
						</label>
						<label class="tag_field">
							<?php $text = br2nl($wo['event']['description']); ?> 
							<textarea name="event-description" id="event-description" placeholder=" " rows="5"><?php echo $text; ?></textarea>
							<span><?php echo $wo['lang']['event']; ?> <?php echo $wo['lang']['description']; ?></span>
						</label>
						<label class="tag_field">
							<input id="event-locat" name="event-locat" type="text" placeholder=" " value="<?php echo $wo['event']['location']; ?>">
							<span><?php echo $wo['lang']['location']; ?></span>
						</label>
						<?php if ($wo['config']['google_map'] == 1) { ?>
							<div id="review-location">
								<div id="place">
									<iframe width="100%" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=<?php echo $wo['event']['location']; ?>&language=en"></iframe><br><br>
								</div>
							</div>
						<?php } ?>
						<div class="tag_alone_label">
							<label><?php echo $wo['lang']['event_start']; ?></label>
						</div>
						<div class="row">
							<div class="col-lg-6">
								<label class="tag_field">
									<input type="text" class="date" id="event-start" name="event-start-date" autocomplete="off" placeholder=" " value="<?php echo $wo['event']['start_edit_date']; ?>">
									<span><?php echo $wo['lang']['start_date']; ?></span>
								</label>
							</div>
							<div class="col-lg-6">
								<label class="tag_field">
									<input type="text" id="event-start-time" class="time1" name="event-start-time" autocomplete="off" placeholder=" " value="<?php echo $wo['event']['start_time']; ?>">
									<span><?php echo $wo['lang']['start_time']; ?></span>
								</label>
							</div>
						</div>
						<div class="tag_alone_label">
							<label><?php echo $wo['lang']['event_end']; ?></label>
						</div>
						<div class="row">
							<div class="col-lg-6">
								<label class="tag_field">
									<input type="text" class="date1" name="event-end-date" id="event-end-date" autocomplete="off" placeholder=" " value="<?php echo $wo['event']['end_edit_date']; ?>">
									<span><?php echo $wo['lang']['end_date']; ?></span>
								</label>
							</div>
							<div class="col-lg-6">
								<label class="tag_field">
									<input type="text" id="event-end-time" class="time1" name="event-end-time" autocomplete="off" placeholder=" " value="<?php echo $wo['event']['end_time']; ?>">
									<span><?php echo $wo['lang']['end_time']; ?></span>
								</label>
							</div>
						</div>
						<div class="setting-general-alert setting-update-alert" id="event-alert"></div>
						<div class="text-center">
							<a class="btn btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=my-events'); ?>" data-ajax="?link1=my-events">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> <?php echo $wo['lang']['go_back'];?>
							</a>
							<button class="btn btn-main btn-mat btn-mat-raised disable_btn" type="submit"><?php echo $wo['lang']['save']; ?></button>
						</div>
					</div>
				</div>
				<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
				<input type="file" name="event-cover" class="hidden" id="event-cover" accept="image/*">
			</form>
		</div>
	</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery-ui-timepicker-addon@1.6.3/dist/jquery-ui-timepicker-addon.min.js"></script>
<script>
  jQuery(document).ready(function($) {
  	$( ".date" ).datepicker({ dateFormat: 'yy-mm-dd', minDate: 'today'});
      $( ".date1" ).datepicker({ dateFormat: 'yy-mm-dd', minDate: '+1day'});
      $( ".time1" ).timepicker();

      $("#event-locat").change(function(event) {
        if ($(this).val().length >= 3) {
          $("#review-location #place").html('<iframe width="100%" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=' + $("#event-locat").val() + '&language=en"></iframe><br><br>')
        }else{
          $("#review-location #place").html('<iframe width="100%" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=us&language=en"></iframe><br><br>')
        }
      });

      $("#event-cover").change(function(event) {
        $("#wow_fcov_img_holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
      });

      $('#update-event').ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=update-event&eid=<?php echo $wo['event']['id']; ?>',
            beforeSend: function() {
              $('#update-event').find('.disable_btn').attr('disabled','disabled');
            },
            success: function(data) {
              if (data['status'] == 200) {
                $("#event-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
                window.location = data['url'];
              } else if (data['message']) {
                $("#event-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
              } 
              $('#update-event').find('.disable_btn').removeAttr("disabled");
            }
      });
  });
</script>