<?php
$online = '';
$time     = time() - 60;
if ($wo['user-list']['lastseen'] > $time) {
	$online = 'online';
}
?>
<div>
	<a class="user wow_content" href="<?php echo $wo['user-list']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['user-list']['username'];?>" title="<?php echo $wo['user-list']['name'];?>">
		<img alt="<?php echo $wo['user-list']['name'];?>" src="<?php echo $wo['user-list']['avatar'];?>" />
		<h4 class="text-center truncate"><?php echo $wo['user-list']['name'];?></h4>
	</a>
</div>