<?php echo Wo_LoadPage('forum/headers/header'); ?>
<div class="row" id="forumsadd">
	<div class="col-xl-1"></div>
	<div class="col-xl-10">
		<div class="page-margin wow_content wow_sett_content">
			<div class="valign wo_page_hdng">
				<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z"></path></svg></span> <?php echo $wo['lang']['edit_topic']; ?> (<?php echo $wo['thread']['headline']; ?>)
			</div>
			<form class="form" id="editopic" method="post">
				<div id="editopic-alert"></div>
				<label class="tag_field">
					<input type="text" name="headline" id="headline" placeholder=" " value="<?php echo $wo['thread']['orginal_headline']; ?>">
					<span><?php echo $wo['lang']['subject']; ?></span>
				</label>
				<div class="form-group">
					<textarea rows="10" class="form-control" id="topicpostcont" name="topicpost"><?php echo br2nlf($wo['thread']['post']); ?></textarea>
				</div>
				<div class="text-center">
					<button class="btn btn-main btn-mat btn-mat-raised disable_btn" id="forum-search-btn" type="submit"><?php echo $wo['lang']['save']; ?></button>
				</div>
			</form>
		</div>
		<div class="clear"></div>
	</div>
	<div class="col-xl-1"></div>
</div>
<?php echo Wo_LoadPage('forum/headers/footer'); ?>

<script>
jQuery(document).ready(function($) {
	$('#editopic').ajaxForm({
	      url: Wo_Ajax_Requests_File()  +  '?f=editopic&tid=<?php echo $wo['thread']['id']; ?>&hash=' + $('.main_session').val(),
	      beforeSend: function() {
			$('#editopic').find('.disable_btn').attr('disabled','disabled');
	      },
	      success: function(data) {
	        scrollToTop();
	        if (data['status'] == 200) {
	         	$("#editopic-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
	          	window.location = data['url'];
	        } else {
	         	$("#editopic-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
	        } 
			$('#editopic').find('.disable_btn').removeAttr("disabled");
	      }
	});

	$("#topicpostcont").bbcode()
	$("#topicpostcont").autogrow({vertical: true, horizontal: false});

});
</script>