<?php echo Wo_LoadPage('forum/headers/header'); ?>
<div role="tabpanel" class="tab-pane active" id="members">
	<div class="page-margin wow_content wow_sett_content">
		<div class="valign wo_page_hdng">
			<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z"></path></svg></span> <?php echo $wo['lang']['list_of_users']; ?>
		</div>
		<div class="valign tag_forum_memb_abc">
			<?php foreach (range('a', 'z') as $char): ?>
				<a class="<?php if ($wo['char'] == $char) echo 'active'; ?>" href="<?php echo Wo_SeoLink("index.php?link1=forum-members-byname&char=".$char); ?>"><?php echo strtoupper($char); ?></a>
			<?php endforeach; ?>
        </div>
		<ul class="list-unstyled valign tag_forum_memb_main_head">
			<li class="lchk"></li>
			<li class="llnk"><?php echo $wo['lang']['name']; ?></li>
			<li class="lcrt"><?php echo $wo['lang']['joined']; ?></li>
			<li class="lclk"><?php echo $wo['lang']['posts']; ?></li>
		</ul>
		<ul class="list-unstyled mb-0 tag_forum_memb_main_content" id="mbrs">
			<?php if (count($wo['members']) > 0): ?>
			<?php foreach ($wo['members'] as $wo['member']): ?>
				<li class="valign forum-mbr-list" id="<?php echo $wo['member']['id']; ?>">
					<div class="lchk">
						<a href="<?php echo $wo['config']['site_url'];?>/<?php echo $wo['member']['username'] ?>" data-ajax="?link1=timeline&u=<?php echo $wo['member']['username'] ?>"><img src="<?php echo $wo['member']['avatar']?>" width="30" height="30" alt=""></a>
					</div>
					<div class="llnk">
						<a href="<?php echo $wo['config']['site_url'];?>/<?php echo $wo['member']['username'] ?>" data-ajax="?link1=timeline&u=<?php echo $wo['member']['username'] ?>"><?php echo $wo['member']['name'] ?></a>
					</div>
					<div class="lcrt"><?php echo Wo_Time_Elapsed_String($wo['member']['joined']) ?></div>
					<div class="lclk"><?php echo($wo['member']['forum_posts']) ?></div>
				</li>
			<?php endforeach; ?>
			<?php else: ?>
				<?php echo '<div class="empty_state"><svg height="512" viewBox="0 0 32 32" width="512" xmlns="http://www.w3.org/2000/svg"><path d="m26 32h-20c-3.314 0-6-2.686-6-6v-20c0-3.314 2.686-6 6-6h20c3.314 0 6 2.686 6 6v20c0 3.314-2.686 6-6 6z" fill="#fff9dd"/><g fill="#ffe777"><circle cx="10.667" cy="14.917" r="1.333"/><path d="m12.447 17.183c-.673.507-1.113 1.32-1.113 2.233v.167h-2.834c-.273 0-.5-.227-.5-.5v-.333c0-1.013.82-1.833 1.833-1.833h1.667c.347 0 .673.1.947.266z"/><circle cx="21.333" cy="14.917" r="1.333"/><path d="m24 18.75v.333c0 .273-.227.5-.5.5h-2.833v-.167c0-.913-.44-1.727-1.113-2.233.273-.167.6-.267.947-.267h1.667c1.012.001 1.832.821 1.832 1.834z"/></g><circle cx="16" cy="14.583" fill="#ffd200" r="2"/><path d="m17.833 17.583h-3.667c-1.011 0-1.833.822-1.833 1.833v1c0 .276.224.5.5.5h6.333c.276 0 .5-.224.5-.5v-1c.001-1.01-.822-1.833-1.833-1.833z" fill="#ffd200"/></svg>' . $wo['lang']['no_members_found'] .  '</div>'; ?>
			<?php endif; ?>
		</ul>
	</div>
    <div class="posts_load">
        <?php if (count($wo['members']) >= 1): ?>
        <div class="load-more">
            <button class="btn btn-default text-center pointer" id="forum-mbrs-load"><span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"></path></svg></span> <?php echo $wo['lang']['load_more_users'] ?></button>
        </div>
        <?php endif ?>
    </div>  
	<div class="clear"></div>
</div>
<?php echo Wo_LoadPage('forum/headers/footer'); ?>

<script>
    jQuery(document).ready(function($) {
      var delay = (function(){
        var timer = 0;
        return function(callback, ms){
          clearTimeout (timer);
          timer = setTimeout(callback, ms);
        };
      })();

      $("#search-members").keyup(function(event) {
          delay(function(){
          if ($("#search-members").val().trim()) {
              $.ajax({
                url: Wo_Ajax_Requests_File(),
                type: 'GET',
                data: { f:"search-forum-mbrs",
                        keyword:$("#search-members").val(),
                        orderby:$("#sort_mbr_by").val()
                      },
                dataType: "json",
                success: function(data){
                  $(".posts_load").remove()
                  if (data['status'] == 200) {
                    $("#mbrs").html(data['html'])
                  }
                  else if(data['status'] == 404){
                    $("#mbrs").html('<tr> <td colspan="7" class="text-center" style="padding:40px 40px;" >' + data['html'] + '</td></tr>')
                  }
                }
              })}
          }, 1000 );
      });

      $("#forum-mbrs-load").click(function () {
		  $.ajax({
			 url: Wo_Ajax_Requests_File(),
			 type: 'GET',
			 dataType: 'json',
			 data: {
				f:"forum-mbrs-load",
				offset:($(".forum-mbr-list").length > 0) ? $(".forum-mbr-list:last").attr('id') : 0
			 },
			 success:function(data){
				if (data['status'] == 200) {
					$("#mbrs").append(data['html'])
				 }
				 else{
				   $(".posts_load").remove()
				 }
			 }
		  });
      });

      $("#adv-mbr-search input").keyup(function(event) {
        var empty = false;
        $("#adv-mbr-search input[type=text]").each(function(index, el) {
            if ($(this).val() == '') {
              empty = true;
            }
        });

        if (empty) {
          $("#adv-mbr-search input[type=submit]").attr('disabled','disabled')
        }
        if(!empty){
          $("#adv-mbr-search input[type=submit]").removeAttr('disabled')
        }
      });
 });
</script>