<?php echo Wo_LoadPage('forum/headers/header'); ?>
<div role="tabpanel" class="tab-pane active" id="showthread">
	<div class="page-margin wow_content wow_sett_content">
		<div class="valign wo_page_hdng">
			<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M10,9V5L3,12L10,19V14.9C15,14.9 18.5,16.5 21,20C20,15 17,10 10,9Z"></path></svg></span> <?php echo $wo['lang']['my'] ?> <?php echo $wo['lang']['replies'] ?>
		</div>
		<?php if (count($wo['messages']) > 0): ?>
			<ul class="list-unstyled valign tag_forum_memb_main_head tag_my_reply_hd">
				<li class="myfrmsbj"><?php echo $wo['lang']['subject']; ?></li>
				<li class="myfrmnme"><?php echo $wo['lang']['forum']; ?></li>
				<li class="myfrmopt"></li>
			</ul>
			<ul class="list-unstyled mb-0 tag_forum_memb_main_content" id="mymessage-list">
				<?php foreach ($wo['messages'] as $wo['message']): ?>
					<?php echo Wo_LoadPage("forum/includes/mymessage-list"); ?>
				<?php endforeach; ?>
			</ul>
		<?php else: ?>
			<?php echo '<div class="empty_state"><svg height="512" viewBox="0 0 32 32" width="512" xmlns="http://www.w3.org/2000/svg"><path d="m26 32h-20c-3.314 0-6-2.686-6-6v-20c0-3.314 2.686-6 6-6h20c3.314 0 6 2.686 6 6v20c0 3.314-2.686 6-6 6z" fill="#ffe6e2"/><path d="m14.667 12.668v-2.835c0-.201-.12-.382-.305-.461-.184-.078-.399-.038-.543.102l-5.667 5.5c-.097.095-.152.224-.152.359s.055.265.152.359l5.667 5.5c.145.14.359.179.543.102.185-.078.305-.26.305-.461v-2.833h.945c3.091 0 5.94 1.68 7.436 4.381l.014.025c.089.163.259.26.439.26.041 0 .083-.005.124-.016.22-.055.375-.255.375-.483 0-5.183-4.171-9.41-9.333-9.499z" fill="#fc573b"/></svg>' . $wo['lang']['no_replies_found'] .  '</div>'; ?>
		<?php endif; ?>	
	</div>
	<div class="posts_load">
		<?php if (count($wo['messages']) > 0): ?>
	        <div class="load-more">
	            <button class="btn btn-default text-center pointer load-my-replies"><span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"></path></svg></span> <?php echo $wo['lang']['load_more'] ?> <?php echo $wo['lang']['replies'] ?></button>
	        </div>
		<?php endif ?>
	</div>  
</div>
<div class="clear"></div>
<?php echo Wo_LoadPage('forum/includes/delete-reply'); ?>
<?php echo Wo_LoadPage('forum/headers/footer'); ?>

<script>
	$(".load-my-replies").click(function () {
        $.ajax({
             url: Wo_Ajax_Requests_File(),
             type: 'GET',
             dataType: 'json',
             data: {
                f:"load-my-thread-replies",
                offset:($(".my-thread-reply-list").length > 0) ? $(".my-thread-reply-list:last").attr('data-thread-reply') : 0
             },
             success:function(data){
                if (data['status'] == 200) {
                    $("#mymessage-list").append(data['html'])
                 }
                 else{
                   $(".posts_load").remove()
                 }
             }
		});
    });
</script>