<?php echo Wo_LoadPage('forum/headers/header'); ?>
<div role="tabpanel" class="tab-pane active" id="search">
	<div id="forum-search-container" class="page-margin wow_content wow_sett_content">
		<div class="valign wo_page_hdng">
			<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z"></path></svg></span> <?php echo $wo['lang']['search'];?>
		</div>
		<form id="forum-search" action="<?php echo Wo_SeoLink('index.php?link1=forum-search-result');?>" method="get" class="forum form-horizontal">
			<input type="hidden" name="mode" value="search">
			<div class="row">
				<div class="col-xl-6">
					<label class="tag_field">
						<textarea rows="7" name="search-terms" placeholder=" " id="search-subject"></textarea>
						<span><?php echo $wo['lang']['search_for_term']; ?></span>
					</label>
					<span class="help-block"><?php echo $wo['lang']['search_terms_more4']; ?></span>
				</div>
				<div class="col-xl-6">
					<label class="tag_field">
						<select id="search-only" name="search-only">
							<option value="0" ><?php echo $wo['lang']['search_subject_only']; ?></option>
							<option value="1" ><?php echo $wo['lang']['search']; ?> <?php echo $wo['lang']['post']; ?></option>
						</select>
						<span><?php echo $wo['lang']['search_type']; ?></span>
					</label>
					<label class="tag_field">
						<select id="search-in" name="search-in">
							<option value="forums"><?php echo $wo['lang']['search_in_forums']; ?></option>
							<option value="messages"><?php echo $wo['lang']['search_in_messages']; ?></option>
							<option value="threads" selected><?php echo $wo['lang']['search_in_threads']; ?></option>
						</select>
						<span><?php echo $wo['lang']['search_in']; ?></span>
					</label>
					<label class="tag_field">
						<select id="section" name="section">
							<?php foreach ($wo['sections'] as $wo['section']): ?>
								<option value="<?php echo $wo['section']['id']; ?>"><?php echo $wo['section']['section_name']; ?></option>
							<?php endforeach; ?>
						</select>
						<span><?php echo $wo['lang']['search_section']; ?></span>
					</label>
				</div>
			</div>
			<div class="text-center">
				<button class="btn btn-main btn-mat btn-mat-raised" id="forum-search-btn" type="submit"><?php echo $wo['lang']['search']; ?></button>
			</div>
		</form>
	</div>
	<div class="clear"></div>
</div>
<?php echo Wo_LoadPage('forum/headers/footer'); ?>

<script>
	jQuery(document).ready(function($) {
        $("#forum-search").submit(function(event) {
	        var empty = $("#search-subject").val();
            if ($("#search-subject").val().length < 4) {
            	event.preventDefault();
            	$("#search-terms").addClass('alert alert-danger');
            	scrollToTop();
            	$("#search-subject").focus();
            }
        });
	});
</script>