<div class="col-lg-4 col-md-6 tag_main_blog_col" data-rm-blog="<?php echo $wo['blog']['id']; ?>">
	<div class="tag_main_blog" id="<?php echo $wo['blog']['id']; ?>">
		<a href="<?php echo $wo['blog']['url']; ?>" class="avatar">
			<img src="<?php echo $wo['blog']['thumbnail']; ?>" alt="<?php echo $wo['blog']['title']; ?>">
		</a>
		<a class="postCategory" href="<?php echo $wo['blog']['category_link']; ?>" data-ajax="?link1=blog-category&id=<?php echo $wo['blog']['category']; ?>"><?php echo $wo['blog_categories'][$wo['blog']['category']]; ?></a>
		<div class="info">
			<h2 class="art-title"><a href="<?php echo $wo['blog']['url']; ?>"><?php echo $wo['blog']['title']; ?></a></h2>
			<div class="postMeta--author-text truncate">
				<a href="<?php echo $wo['blog']['author']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['blog']['author']['username']; ?>"><?php echo $wo['blog']['author']['name']; ?></a>
				<span class="middot">·</span>
				<time><?php echo date("d M Y",$wo['blog']['posted']); ?></time>
			</div>
		</div>
	</div>
</div>