<div class="group-messages-wrapper messages-wrapper valign" id="messageId_<?php echo $wo['chatMessage']['id'] ?>" data-group-tmessage-id="<?php echo $wo['chatMessage']['id'] ?>" data-message-id="<?php echo $wo['chatMessage']['id'] ?>">
	<?php if (!$wo['chatMessage']['onwer']): ?>
		<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u='.$wo['chatMessage']['user_data']['username']);?>" data-ajax="?link1=timeline&u=<?php echo $wo['chatMessage']['user_data']['username']?>">
			<img class="user-avatar<?php echo ($wo['chatMessage']['onwer'] == 1) ? '-right' : '-left';?>" src="<?php echo $wo['chatMessage']['user_data']['avatar'] ?>" alt="Profile Picture">
		</a>
	<?php endif; ?>
	<div class="message <?php echo ($wo['chatMessage']['onwer']) ? 'outgoing' : 'incoming';?>">
		<?php if (!empty($wo['chatMessage']['text'])): ?>
			<p class="message-text" dir="auto">
				<?php if($wo['chatMessage']['type_two'] == 'contact'): 
					$json = json_decode(trim(htmlspecialchars_decode($wo['chatMessage']['text'])), true);
					echo $json['Value'] . ' (' . $json['Key'] . ')';
				?>
				<?php else: ?>
					<?php echo $wo['chatMessage']['text']; ?>
				<?php endif;?>
			</p>
		<?php endif; ?>
		<div class="clear"></div>
		<div class="message-media">
			<?php  
				if(isset($wo['chatMessage']['media']) && !empty($wo['chatMessage']['media'])) {
					$media = array('type' => 'chatMessage', 'storyId' => $wo['chatMessage']['id'], 'filename' => $wo['chatMessage']['media'], 'name' => $wo['chatMessage']['mediaFileName']); 
					echo Wo_DisplaySharedFile($media, 'chat');   
				} 
			?>
		</div>
		<div class="valign like-stat stat-item post-like-status">
			<span class="like-emo post-reactions-icons-m-<?php echo $wo['chatMessage']['id']; ?>"><?php echo Wo_GetPostReactions($wo['chatMessage']['id'],'message');?></span>
		</div>
		<div class="clear"></div>
	</div>
	<div class="dropup valign tag_chat_opts">
		<?php //if ($wo['chatMessage']['onwer'] == 0) { ?>
			<div class="pointer deleteMessage dropdown-toggle" data-toggle="dropdown" role="button">
				<svg xmlns="http://www.w3.org/2000/svg" width="19" height="19" viewBox="0 0 24 24" opacity="0.5"><path fill-rule="evenodd" clip-rule="evenodd" fill="currentColor" d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-2a8 8 0 1 0 0-16 8 8 0 0 0 0 16zm-5-7h2a3 3 0 0 0 6 0h2a5 5 0 0 1-10 0zm1-2a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm8 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z" /></svg>
			</div>
			<div class="dropdown-menu tag_chat_reacts">
				<ul class="reactions-box" data-id="<?php echo $wo['chatMessage']['id']; ?>">
					<?php if (!empty($wo['reactions_types'])) {
						foreach ($wo['reactions_types'] as $key => $value) {
							if ($value['status'] == 1) {
						 ?>
						<li class="valign reaction reaction-<?php echo $value['id'];?>" data-reaction="<?php echo $value['name'];?>" data-reaction-id="<?php echo $value['id'];?>" data-reaction-lang="<?php echo $value['name'];?>" title="<?php echo $value['name'];?>" data-post-id="<?php echo $wo['chatMessage']['id']; ?>" onclick="Wo_RegisterMessageReaction(this,'<?php echo($value['wowonder_small_icon']) ?>',<?php echo($value['is_html']) ?>);">
							<?php if (preg_match("/<[^<]+>/",$value['wowonder_icon'],$m)) {
									echo($value['wowonder_icon']);
								 }
								 else{ ?>
								<img src="<?php echo($value['wowonder_icon']) ?>">
							<?php } ?>
						</li>
					<?php } } } ?>
				</ul>
			</div>
		<?php //} ?>
	</div>
	<div class="clear"></div>
	<?php if($wo['chatMessage']['user_data']['user_id'] == $wo['user']['user_id']) { ?>
		<div class="message-seen"></div>
		<div class="clear"></div>
	<?php } ?>
	<div class="message-typing"></div>
</div>
<div class="clear"></div>