<div class="tag_review_list" id="review-<?php echo $wo['review']['id']?>" data-user-review="<?php echo $wo['review']['id'];?>">
	<div class="review_list_head">
		<div class="valign review-meta-desc">
			<div class="reviewMeta--author-avatar">
				<a href="<?php echo $wo['review']['user_data']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['review']['user_data']['username'];?>"><img src="<?php echo $wo['review']['user_data']['avatar'];?>" alt="<?php echo $wo['review']['user_data']['name']; ?>" /></a>
			</div>
			<div class="reviewMeta--author-text">
				<span class="user-popover" data-id="<?php echo $wo['review']['user_data']['id'];?>" data-type="<?php echo $wo['review']['user_data']['type'];?>">
					<a class="main bold" href="<?php echo $wo['review']['user_data']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['review']['user_data']['username'];?>"><?php echo $wo['review']['user_data']['name']; ?></a>
				</span>
			</div>
		</div>
		<div class="Review-rating">
			<?php 
				for ($i=0; $i < $wo['review']['valuation']; $i++) { 
					echo '<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="22" viewBox="0 0 24 24" width="22" fill="#FF9800" class=""><g><path d="M0,0h24v24H0V0z" fill="none"></path><path d="M0,0h24v24H0V0z" fill="none"></path></g><g><path d="M12,17.27l4.15,2.51c0.76,0.46,1.69-0.22,1.49-1.08l-1.1-4.72l3.67-3.18c0.67-0.58,0.31-1.68-0.57-1.75l-4.83-0.41 l-1.89-4.46c-0.34-0.81-1.5-0.81-1.84,0L9.19,8.63L4.36,9.04c-0.88,0.07-1.24,1.17-0.57,1.75l3.67,3.18l-1.1,4.72 c-0.2,0.86,0.73,1.54,1.49,1.08L12,17.27z"></path></g></svg>';
				}
			?>
		</div>
	</div>
	<p class="prod_review-desc">
		<?php if (strlen($wo['review']['review']) > 250):?>
            <?php echo mb_substr($wo['review']['review'],0,250,"UTF-8") . "..."; ?> <span class="main pointer" onclick="$('#review-read-<?php echo $wo['review']['id'];?>').modal();"><?php echo $wo['lang']['read_more']; ?></span>
        <?php else:?>
            <?php echo $wo['review']['review']; ?>
        <?php endif;?>
	</p>
	<?php if (strlen($wo['review']['review']) > 250):?>
		<div class="modal fade" id="review-read-<?php echo $wo['review']['id'];?>" role="dialog">
			<div class="modal-dialog wow_mat_mdl">
				<div class="modal-content">
					<div class="modal-header">
						<h4 class="modal-title"><?php echo $wo['review']['user_data']['name']; ?></h4>
					</div>
					<div class="modal-body">
						<p><?php echo $wo['review']['review'];?></p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default btn-mat" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['close'];?></button>
					</div>
				</div>
			</div>
		</div>
	<?php endif;?>
</div>