<div class="page-margin">
	<div class="container">
		<h2 class="tag_page_title m5"><?php echo $wo['lang']['pages']; ?></h2>
		<ul class="list-unstyled tag_page_nav">
			<li class="separate"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=pages'); ?>" data-ajax="?link1=pages"><?php echo $wo['lang']['my_pages'] ?></a></li>
			<li class="active"><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=suggested-pages'); ?>" data-ajax="?link1=suggested-pages"><?php echo $wo['lang']['suggested_pages'] ?></a></li>
			<li><a class="btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=liked-pages'); ?>" data-ajax="?link1=liked-pages"><?php echo $wo['lang']['liked_pages'] ?></a></li>
		</ul>
		<?php if ($wo['config']['pro'] == 1) { ?>
		<div class="page-margin">
			<p class="bold"><?php echo $wo['lang']['promoted'] ?></p>
			<div class="wow_content">
				<?php
					$promoted_page = Wo_GetPromotedPage();
					if (count($promoted_page) > 0) {
						foreach ($promoted_page as $wo['page']) {
							echo Wo_LoadPage('page/promoted-pages-list');
						}
					} else {
						echo '<div class="empty_state"><svg height="512" viewBox="0 0 32 32" width="512" xmlns="http://www.w3.org/2000/svg"><path d="m26 32h-20c-3.314 0-6-2.686-6-6v-20c0-3.314 2.686-6 6-6h20c3.314 0 6 2.686 6 6v20c0 3.314-2.686 6-6 6z" fill="#ffe6e2"/><path d="m22.167 11.333h-2.833v-1.5c0-.643-.523-1.167-1.167-1.167h-8.167c0-.368-.299-.666-.667-.666s-.666.298-.666.667v.5 7.333 6.833c0 .369.298.667.666.667s.667-.298.667-.667v-6.333h2.333v1.5c0 .643.523 1.167 1.167 1.167h8.667c.643 0 1.167-.523 1.167-1.167v-6c-.001-.643-.524-1.167-1.167-1.167z" fill="#fc573b"/></svg>' . $wo['lang']['no_pages_found'] . '</div>';
					}
				?>
			</div>
		</div>
		<?php } ?>
		<div class="page-margin">
			<p class="bold"><?php echo $wo['lang']['suggested_pages'] ?></p>
			<div class="wow_content">
				<?php
					$pages = Wo_PageSug(50);
					if (count($pages) > 0) {
						foreach ($pages as $wo['page']) {
							$wo['page']['Wo_PageSug'] = true;
							echo Wo_LoadPage('page/pages-list');
						}
					} else {
						echo '<div class="empty_state"><svg height="512" viewBox="0 0 32 32" width="512" xmlns="http://www.w3.org/2000/svg"><path d="m26 32h-20c-3.314 0-6-2.686-6-6v-20c0-3.314 2.686-6 6-6h20c3.314 0 6 2.686 6 6v20c0 3.314-2.686 6-6 6z" fill="#ffe6e2"/><path d="m22.167 11.333h-2.833v-1.5c0-.643-.523-1.167-1.167-1.167h-8.167c0-.368-.299-.666-.667-.666s-.666.298-.666.667v.5 7.333 6.833c0 .369.298.667.666.667s.667-.298.667-.667v-6.333h2.333v1.5c0 .643.523 1.167 1.167 1.167h8.667c.643 0 1.167-.523 1.167-1.167v-6c-.001-.643-.524-1.167-1.167-1.167z" fill="#fc573b"/></svg>' . $wo['lang']['no_pages_found'] . '</div>';
					}
				?>
			</div>
		</div>
	</div>
</div>