<div class="page-margin">
	<div class="container">
		<h2 class="tag_page_title m5">My Apps</h2>
		<div class="page-margin wow_content wow_sett_content">
			<div class="valign wo_page_hdng">
				<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M5,3H19A2,2 0 0,1 21,5V19A2,2 0 0,1 19,21H5A2,2 0 0,1 3,19V5A2,2 0 0,1 5,3M7,7V9H9V7H7M11,7V9H13V7H11M15,7V9H17V7H15M7,11V13H9V11H7M11,11V13H13V11H11M15,11V13H17V11H15M7,15V17H9V15H7M11,15V17H13V15H11M15,15V17H17V15H15Z"></path></svg></span> App Details
			</div>
			<div class="valign">
				<ul class="valign nav nav-tabs tag_switch_noti" role="tablist">
					<li role="presentation"><a href="#keys" class="active" aria-controls="keys" role="tab" data-toggle="tab">App Keys</a></li>
					<li role="presentation"><a href="#app-setting" aria-controls="app-setting" role="tab" data-toggle="tab">App Settings</a></li>
				</ul>
			</div>
			<div class="tab-content" id="tabs">
				<div class="tab-pane active" id="keys">
					<label class="tag_field">
						<input id="app_id" name="app_id" type="text" readonly placeholder=" " value="<?php echo $wo['app']['app_id']; ?>" onClick="this.select();">
						<span>App ID</span>
					</label>
					<div class="help-block">Your application ID.</div>
					<label class="tag_field">
						<input id="app_secret" name="app_secret" type="text" readonly placeholder=" " value="<?php echo $wo['app']['app_secret']; ?>" onClick="this.select();">
						<span>App secret</span>
					</label>
					<div class="help-block">Your application secret key.</div>
					<div class="text-center">
						<a class="btn btn-mat" data-ajax="?link1=apps" href="<?php echo Wo_SeoLink('index.php?link1=apps');?>">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> My Apps
						</a>
					</div>
				</div>
				<div class="tab-pane" id="app-setting">
					<form class="app-update-form" method="post">
						<div class="row">
							<div class="col-md-4 pl15">
								<div class="tag_alone_label">
									<label><?php echo $wo['lang']['image'];?></label>
								</div>
								<div class="wow_fcov_image crt_eve_image">
									<div id="wow_fcov_img_holder"></div>
									<div class="valign upload_ad_image" onclick="document.getElementById('app_avatar').click(); return false">
										<div class="btn btn-mat btn-default upload_ad_image_content">
											<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1,3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z"></path></svg> <?php echo $wo['lang']['choose_image'] ?>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-8">
								<label class="tag_field">
									<input id="app_name" name="app_name" type="text" max="32" placeholder=" " value="<?php echo $wo['app']['app_name']; ?>">
									<span><?php echo $wo['lang']['name']; ?></span>
								</label>
								<div class="help-block">Your application name. This is used to attribute the source user-facing authorization screens. 32 characters max.</div>
								<label class="tag_field">
									<input id="app_website_url" name="app_website_url" type="url" placeholder=" " value="<?php echo $wo['app']['app_website_url']; ?>">
									<span>Domain</span>
								</label>
								<div class="help-block">Your application's publicly accessible home page.</div>
								<label class="tag_field">
									<input id="app_callback_url" name="app_callback_url" type="url" placeholder=" " value="<?php echo $wo['app']['app_callback_url']; ?>">
									<span>Redirect URL</span>
								</label>
								<div class="help-block">Where should we return after successfully authenticating?</div>
								<label class="tag_field">
									<textarea name="app_description" id="app_description" rows="4" placeholder=" " max="200"><?php echo $wo['app']['app_description']; ?></textarea>
									<span>Description</span>
								</label>
								<div class="help-block">Your application description, which will be shown in user-facing authorization screens. Between 10 and 200 characters max.</div>
								<div class="app-update-alert setting-update-alert"></div>
								<div class="text-center">
									<a class="btn btn-mat disable_btn" data-ajax="?link1=apps" href="<?php echo Wo_SeoLink('index.php?link1=apps');?>">
										<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> My Apps
									</a>
									<button class="btn btn-main btn-mat btn-mat-raised disable_btn" name="save_setting" id="save-setting" type="submit"><?php echo $wo['lang']['save']; ?></button>
								</div>
							</div>
						</div>
						<div class="hidden">
							<input name="app_avatar" id="app_avatar" type="file" accept="image/x-png, image/gif, image/jpeg">
						</div>
						<input name="app_id" id="app_id" type="hidden" value="<?php echo $wo['app']['id']; ?>">
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
$("#app_avatar").change(function(event) {
	$("#wow_fcov_img_holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
});

  $(function() {
    $('form.app-update-form').ajaxForm({
      url: Wo_Ajax_Requests_File() + '?f=apps&s=update_app',
      beforeSend: function() {
        $('.app-update-form').find('.disable_btn').attr('disabled','disabled');
      },
      success: function(data) {
        if (data.status == 200) {
          $('[id^=app-name]').text(data.name);
          $('.app-avatar').attr('src', data.image);
          $('.app-update-alert').html('<div class="alert alert-success">' + data.message + '</div>');
          $('.alert-success').fadeIn('fast', function() {
             $(this).delay(2500).slideUp(500, function() {
                $(this).remove();
              });
          });
        } else {
            var errors = data.errors.join("<br>");
            $('.app-update-alert').html('<div class="alert alert-danger">' + errors + '</div>');
            $('.alert-danger').fadeIn(300);
        }
        $('.app-update-form').find('.disable_btn').removeAttr("disabled");
      }
    });
  });
</script>