<div class="page-margin">
    <div class="container">
		<h2 class="tag_page_title m5"><?php echo $wo['lang']['developers'] ?></h2>
		<?php echo Wo_LoadPage('graph/sidebar') ?>
		<div class="page-margin wow_content p20">
			<p>Our API allows you to retrieve informations from our website via GET request and supports the following query parameters: </p>
			<div class="table-responsive">
				<table class="table table-bordered">
					<thead>
						<tr>
							<th>Name</th>
							<th>Meaning</th>
							<th>Values</th>
							<th>Description</th>
							<th>Required</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><b class="bold">type</b></td>
							<td>Query type.</td>
							<td>get_user_data, posts_data</td>
							<td>This parameter specify the type of the query.</td>
							<td><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20"><path fill="#4CAF50" d="M10.3125,16.09375a.99676.99676,0,0,1-.707-.293L6.793,12.98828A.99989.99989,0,0,1,8.207,11.57422l2.10547,2.10547L15.793,8.19922A.99989.99989,0,0,1,17.207,9.61328l-6.1875,6.1875A.99676.99676,0,0,1,10.3125,16.09375Z" opacity=".99"></path><path fill="#4CAF50" opacity="0.2" d="M12,2A10,10,0,1,0,22,12,10.01146,10.01146,0,0,0,12,2Zm5.207,7.61328-6.1875,6.1875a.99963.99963,0,0,1-1.41406,0L6.793,12.98828A.99989.99989,0,0,1,8.207,11.57422l2.10547,2.10547L15.793,8.19922A.99989.99989,0,0,1,17.207,9.61328Z"></path></svg></td>
						</tr>
						<tr>
							<td><b class="bold">limit</b></td>
							<td>Limit of items.</td>
							<td>LIMIT</td>
							<td>This parameter specify the limit of items. Max:100 | Default:20</td>
							<td><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20"><path fill="#bababa" d="M13.41406,12l3.293-3.293A.99989.99989,0,0,0,15.293,7.293L12,10.58594,8.707,7.293A.99989.99989,0,0,0,7.293,8.707L10.58594,12,7.293,15.293A.99989.99989,0,0,0,8.707,16.707L12,13.41406l3.293,3.293A.99989.99989,0,0,0,16.707,15.293Z"></path><path fill="#bababa" opacity="0.2" d="M19.0708,4.9292A9.99962,9.99962,0,1,0,4.9292,19.0708,9.99962,9.99962,0,1,0,19.0708,4.9292ZM16.707,15.293A.99989.99989,0,1,1,15.293,16.707L12,13.41406,8.707,16.707A.99989.99989,0,0,1,7.293,15.293L10.58594,12,7.293,8.707A.99989.99989,0,0,1,8.707,7.293L12,10.58594l3.293-3.293A.99989.99989,0,0,1,16.707,8.707L13.41406,12Z"></path></svg></td>
						</tr>
					</tbody>
				</table>
			</div>
			<br>
			<div style="font-size:18px;">How to start?</div>
			<hr>
			<ol style="list-style: initial;">
				<li>Create a <a href="<?php echo Wo_SeoLink('index.php?link1=create-app');?>" class="main">development application</a>.<br><br></li>
				<li>Once you have created the app, you'll get APP_ID, and APP_SECRET.<br> <img src="https://s3.postimg.org/4vaacpclf/Screenshot_24.png" alt=""><br><br></li>
				<li>To start the Oauth process, use the link <?php echo $wo['config']['site_url'] ?>/oauth?app_id={YOUR_APP_ID}<br><br></li>
				<li>Once the end user clicks this link, he/she will be redirected to the authorization page.<br><br></li>
				<li>Once the end user authorization the app, he/she will be redirected to your domain name with a GET parameter "code", example: http://yourdomain/?code=XXX<br><br></li>
				<li>
					In your code, to retrieve the authorized user info, you need to generate an access code, please use the code below:<br><br>
					<div class="bold">PHP:</div>
					<?php 
						$code = '<?php
	$app_id = \'YOUR_APP_ID\'; // your application app id
	$app_secret = \'YOUR_APP_SECRET\'; your application app secret
	$code = $_GET[\'code\']; // the GET parameter you got in the callback: http://yourdomain/?code=XXX

	$get = file_get_contents("' . $wo['config']['site_url'] . '/authorize?app_id={$app_id}&app_secret={$app_secret}&code={$code}");

	$json = json_decode($get, true);
	if (!empty($json[\'access_token\'])) {
		$access_token = $json[\'access_token\']; // your access token
	}
?>';
					echo '
						<pre>' . htmlspecialchars($code) . '</pre>
						';
					?>
				</li>
				<li>
					Once you got the access code, simple call the data you would like to retrieve, Example: <br><br>
					<div class="bold">PHP:</div>
					<?php 
						$code = 'if (!empty($json[\'access_token\'])) {
	$access_token = $json[\'access_token\']; // your access token
	$type = "get_user_data"; // or posts_data
	$get = file_get_contents("' . $wo['config']['site_url'] . '/app_api?access_token={$access_token}&type={$type}");
}
';
						echo '<pre>' . htmlspecialchars($code) . '</pre>';
					?>

					<div class="bold">Respond:</div>
					<pre>
<b>Json</b>output
{
	"api_status": "success",
	"api_version": "1.3",
	"user_data": {
		"id": "",
		"username": "",
		"first_name": "",
		"last_name": "",
		"gender": "",
		"birthday": "",
		"about": "",
		"website": "",
		"facebook": "",
		"twitter": "",
		"vk": "",
		"google+": "",
		"profile_picture": "",
		"cover_picture": "",
		"verified": "",
		"url": ""
	}
}
</pre>
				</li>
			</ol>
		</div>
    </div>
</div>