<div class="col-lg-4 col-md-6" data-ad-id="<?php echo $wo['ad']['id']; ?>">
	<div class="wow_content">
		<div class="aemp">
			<div class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M7.41,8.58L12,13.17L16.59,8.58L18,10L12,16L6,10L7.41,8.58Z"></path></svg></a>
				<ul class="dropdown-menu dropdown-menu-right tag_create_menu clearfix" role="menu">
					<li>
						<a href="<?php echo $wo['ad']['chart-url']; ?>">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M11 2.05V13h10.95c-.501 5.053-4.765 9-9.95 9-5.523 0-10-4.477-10-10 0-5.185 3.947-9.449 9-9.95zm2 0A10.003 10.003 0 0 1 21.95 11H13V2.05z"></path><path fill="currentColor" d="M12 22C6.477 22 2 17.523 2 12c0-4.478 2.943-8.268 7-9.542v2.124A8.003 8.003 0 0 0 12 20a8.003 8.003 0 0 0 7.418-5h2.124c-1.274 4.057-5.064 7-9.542 7zm9.95-9H11V2.05c.329-.033.663-.05 1-.05 5.523 0 10 4.477 10 10 0 .337-.017.671-.05 1zM13 4.062V11h6.938A8.004 8.004 0 0 0 13 4.062z"></path></svg> <?php echo $wo['lang']['view_analytics']; ?>
						</a>
					</li>
					<li>
						<a href="<?php echo $wo['ad']['edit-url']; ?>">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M9.243 19H21v2H3v-4.243l9.9-9.9 4.242 4.244L9.242 19zm5.07-13.556l2.122-2.122a1 1 0 0 1 1.414 0l2.829 2.829a1 1 0 0 1 0 1.414l-2.122 2.121-4.242-4.242z"></path><path fill="currentColor" d="M5 19h1.414l9.314-9.314-1.414-1.414L5 17.586V19zm16 2H3v-4.243L16.435 3.322a1 1 0 0 1 1.414 0l2.829 2.829a1 1 0 0 1 0 1.414L9.243 19H21v2zM15.728 6.858l1.414 1.414 1.414-1.414-1.414-1.414-1.414 1.414z"></path></svg> <?php echo $wo['lang']['edit_ads']; ?>
						</a>
					</li>
					<li class="delete-ad" id="<?php echo $wo['ad']['id']; ?>">
						<a href="javascript:void(0);">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" class="hover_path" d="M20 7v14a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7H2V5h20v2h-2zm-9 3v7h2v-7h-2zM7 2h10v2H7V2z"></path><path fill="currentColor" d="M20 7v14a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7H2V5h20v2h-2zM6 7v13h12V7H6zm1-5h10v2H7V2zm4 8h2v7h-2v-7z"></path></svg> <?php echo $wo['lang']['delete_ad']; ?>
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="aid"><a href="<?php echo $wo['ad']['edit-url']; ?>">#<?php echo $wo['ad']['id']; ?></a></div>
		<div class="acomp truncate"><a href="<?php echo $wo['ad']['chart-url']; ?>"><?php echo $wo['ad']['name']; ?></a></div>
		<div class="abid"><?php echo $wo['lang'][$wo['ad']['bidding']]; ?> <?php echo $wo['lang']['bidding']; ?></div>
		<div class="valign">
			<div class="aclck"><svg xmlns="http://www.w3.org/2000/svg" height="22" viewBox="0 0 24 24" width="22"><path fill="currentColor" d="M13 1.07V9h7c0-4.08-3.05-7.44-7-7.93zM4 15c0 4.42 3.58 8 8 8s8-3.58 8-8v-4H4v4zm7-13.93C7.05 1.56 4 4.92 4 9h7V1.07z"/></svg> <?php echo $wo['ad']['clicks']; ?> <?php echo $wo['lang']['clicks']; ?></div>
			<div class="avew"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path fill="currentColor" d="M12 4C7 4 2.73 7.11 1 11.5 2.73 15.89 7 19 12 19s9.27-3.11 11-7.5C21.27 7.11 17 4 12 4zm0 12.5c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z"/></svg> <?php echo $wo['ad']['views']; ?> <?php echo $wo['lang']['views']; ?></div>
		</div>
		<div class="asts" data-ad-status="<?php echo $wo['ad']['id']; ?>">
			<span class="toggle-user-ad-status pointer" id="<?php echo $wo['ad']['id']; ?>" data-status="<?php echo $wo['ad']['status']; ?>">
				<?php if ($wo['ad']['status'] == 1): ?>
					<span class="valign"><span><span><?php echo $wo['lang']['status']; ?></span>: <?php echo $wo['lang']['active']; ?></span> <svg xmlns="http://www.w3.org/2000/svg" height="22" viewBox="0 0 24 24" width="22"><path fill="<?php echo $wo['config']['btn_background_color'];?>" d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-8.29 13.29c-.39.39-1.02.39-1.41 0L5.71 12.7c-.39-.39-.39-1.02 0-1.41.39-.39 1.02-.39 1.41 0L10 14.17l6.88-6.88c.39-.39 1.02-.39 1.41 0 .39.39.39 1.02 0 1.41l-7.58 7.59z"/></svg></span>
				<?php else: ?>
					<span class="valign"><span><span><?php echo $wo['lang']['status']; ?></span>: <?php echo $wo['lang']['not_active']; ?></span> <svg xmlns="http://www.w3.org/2000/svg" height="22" viewBox="0 0 24 24" width="22"><path fill="currentColor" d="M18 19H6c-.55 0-1-.45-1-1V6c0-.55.45-1 1-1h12c.55 0 1 .45 1 1v12c0 .55-.45 1-1 1zm1-16H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z"/></svg></span>
				<?php endif; ?>
			</span>
		</div>
	</div>
</div>