<div class="modal fade" id="create-password" role="dialog">
	<div class="modal-dialog wow_mat_mdl modal-md" id="modal-dialog-update-info">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><?php echo $wo['lang']['update_your_info']; ?></h4>
            </div>
			<form action="#" method="post" class="create-password">
				<div class="modal-body tag_field_full_margin">
					<div class="error-container"></div>
					<label class="tag_field">
						<input id="username" name="username" type="text" placeholder=" " onkeyup="Wo_CheckUsername(this.value);" autocomplete="off">
						<span><?php echo $wo['lang']['choose_your_username'] ?></span>
					</label>
					<div class="help-block checking"></div>
					<hr class="mb-15">
					<label class="tag_field">
						<input id="new_password" name="new_password" type="password" placeholder=" " autocomplete="off">
						<span><?php echo $wo['lang']['create_your_new_password'] ?></span>
					</label>
					<label class="tag_field">
						<input id="repeat_new_password" name="repeat_new_password" type="password" placeholder=" " autocomplete="off">
						<span><?php echo $wo['lang']['confirm_password'] ?></span>
					</label>
					<input type="hidden" name="user_id" value="<?php echo $wo['user']['user_id']?>">
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default btn-mat disable_btn" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['cancel'] ?></button>
					<button id="create-password-button" type="submit" class="btn btn-mat btn-main"><?php echo $wo['lang']['update'];?></button>
				</div>
			</form>
		</div>
	</div>
</div>