<div class="modal fade" id="delete-comment-reply" role="dialog">
	<div class="modal-dialog modal-md wow_mat_mdl">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><?php echo $wo['lang']['delete_comment']; ?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $wo['lang']['confirm_delete_comment']; ?></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-mat disable_btn" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['cancel'] ?></button>
				<button id="delete-all-reply" type="button" class="btn btn-main btn-mat disable_btn"><?php echo $wo['lang']['delete']; ?></button>
			</div>
		</div>
	</div>
</div>