<div class="modal fade" id="keyboard_shortcuts_box" role="dialog">
	<div class="modal-dialog wow_mat_mdl modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title"><?php echo $wo['lang']['keyboard_shortcuts'];?></h4>
			</div>
			<div class="modal-body">
				<table class="key_shortcts">
					<tbody>
						<tr>
							<th><span>J</span></th>
							<td><?php echo $wo['lang']['keyboard_shortcut_j']; ?></td>
						</tr>
						<tr>
							<th><span>K</span></th>
							<td><?php echo $wo['lang']['keyboard_shortcut_k']; ?></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-mat" data-dismiss="modal" aria-label="Close"><?php echo $wo['lang']['close'] ?></button>
			</div>
		</div>
	</div>
</div>