<div id="ImageModal-<?php echo $wo['message']['id'];?>" class="modal fade image-modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog wow_mat_mdl modal-lg">
		<div class="modal-content">
			<img src="<?php echo $wo['media']['filename'];?>" class="img-responsive">
			<div class="modal-footer">         
				<a href="<?php echo $wo['media']['filename'];?>" download id="delete-all-post" type="button" class="btn btn-mat btn-main"><?php echo $wo['lang']['download'];?></a>
			</div>
		</div>
	</div>
</div>