<div id="ProfileImageModal-<?php echo $wo['user_profile']['user_id'];?>" class="modal fade image-modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="valign tag_lbox_toolbar"><div class="btn btn-mat close-lightbox" data-dismiss="modal" aria-label="Close"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M7.828 11H20v2H7.828l5.364 5.364-1.414 1.414L4 12l7.778-7.778 1.414 1.414z"></path></svg></div></div>
	<div class="modal-dialog">
		<div class="modal-content">
			<img src="<?php echo $wo['user_profile']['avatar'];?>" id="updateImage-<?php echo $wo['user_profile']['user_id']?>" class="rounded-circle">
		</div>
	</div>
</div>